/*
----------------------------
MetaDoom
Actor Definitions
Pinata Items
----------------------------
*/

// Doom 2016-style "pinata" pickups - contextual icons that give you stuff.

// This one fades away!
class MetaHealthPinata : Health
{
	Default
	{
		-COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		Inventory.Amount 2;
		Inventory.PickupMessage "$GOTPINATAHEALTH";
		Inventory.PickupSound "items/health/shard";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	int lifespan;
	
	States
	{
	Spawn:
		PINH A 0;
		PINH A 0 { lifespan = 0; }
	Sit:
		PINH A 4 bright;
		PINH A 4 { lifespan++; }
		PINH A 0 A_JumpIf(lifespan >= 12, "Fade");
		loop;
	Fade:
		PINH A 4 bright A_FadeOut(0.2);
		PINH A 4 A_FadeOut(0.2);
		loop;
	}
}

// This one, not so much.
class MetaHealthPinataPerm : MetaHealthPinata
{
	Default
	{
		Inventory.Amount 4;
	}
	
	States
	{
	Spawn:
		PINH A 4 bright;
		PINH A 4;
		loop;
	}
}	

class MetaArmorPinata : BasicArmorBonus
{
	Default
	{
		-COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		Armor.Savepercent 33.335;
		Armor.Saveamount 4;
		Armor.Maxsaveamount 100;
		Inventory.PickupSound "items/armor/shard";
		Inventory.PickupMessage "$GOTPINATAARMOR";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	States
	{
	Spawn:
		PINH A 4 bright;
		PINH A 4;
		loop;
	}
}

class MetaPinataClip : Clip
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_CLIP";
		Inventory.Amount 5;
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		inventory.pickupsound "items/clip";
		scale 0.75;
		RenderStyle "Add";
	}
	
	States
	{
	Spawn:
		PINM A 4 bright;
		PINM A 4;
		loop;
	}
}

class MetaPinataShell : Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_SHELL";
		Inventory.Amount 2;
		inventory.pickupsound "items/shell";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	States
	{
	Spawn:
		PINM B 4 bright;
		PINM B 4;
		loop;
	}
}

class MetaPinataRocket : RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_ROCKET";
		Inventory.Amount 2;
		inventory.pickupsound "items/rocket";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	States
	{
	Spawn:
		PINM C 4 bright;
		PINM C 4;
		loop;
	}
}

class MetaPinataCell : Cell
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_CELL";
		Inventory.Amount 10;
		inventory.pickupsound "items/cell";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	States
	{
	Spawn:
		PINM D 4 bright;
		PINM D 4;
		loop;
	}
}