/*
----------------------------
MetaDoom
class Definitions
Score Items
----------------------------
*/

// Pointless but fun, these items do nothing but look nice and increase your score.

// 25% chance of spawning a low-scoring item
// 12.5% chance of spawning a high-scoring item
// 0.78% chance of spawning a figurine
class LootSpawner : Actor
{
	Default
	{
		radius 64;
		height 32;
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(64, "Loot1", "Loot2", "Loot6", "Loot7");
		TNT1 A 0 A_Jump(32, "Loot3", "Loot4", "Loot5");
		TNT1 A 0 A_Jump(2, "LootFig");
		stop;
	Loot1:
		TNT1 A 0 A_SpawnItemEx("LootDagger",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot2:
		TNT1 A 0 A_SpawnItemEx("LootChest",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot3:
		TNT1 A 0 A_SpawnItemEx("LootSceptre",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot4:
		TNT1 A 0 A_SpawnItemEx("LootBible",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot5:
		TNT1 A 0 A_SpawnItemEx("LootCrown",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot6:
		TNT1 A 0 A_SpawnItemEx("LootGoblet",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot7:
		TNT1 A 0 A_SpawnItemEx("LootCredits",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	LootFig:
		TNT1 A 0 A_Jump(256, "LootFig1", "LootFig2", "LootFig3", "LootFig4");
		stop;
	LootFig1:
		TNT1 A 0 A_SpawnItemEx("LootFigurine1",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	LootFig2:
		TNT1 A 0 A_SpawnItemEx("LootFigurine2",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	LootFig3:
		TNT1 A 0 A_SpawnItemEx("LootFigurine3",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	LootFig4:
		TNT1 A 0 A_SpawnItemEx("LootFigurine4",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	}
}

class LootItem : ScoreItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT6";
		inventory.pickupsound "items/loot";
		BounceType "Grenade";
		Bouncefactor 0.0;
		WallBouncefactor 1.0;
		-COUNTITEM
		+BLOCKASPLAYER
	}
	
	States
	{
	Spawn:
		LOOT F 0;
		"####" "#" 0;
		goto MoveAround;
	MoveAround:
		"####" "#" 35;
		"####" "#" 0 A_Stop; // Prevents bouncing around wallsliding all day
		goto Sit;
	Sit:
		"####" "#" -1;
		loop;
	}
}

class LootGoblet : LootItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT6";
	}
	
	States
	{
	Spawn:
		LOOT F 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

class LootDagger : LootItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT1";
	}
	
	States
	{
	Spawn:
		LOOT A 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

class LootChest : LootItem
{
	Default
	{
		Inventory.Amount 1000;
		Inventory.PickupMessage "$GOTLOOT2";
	}
	
	States
	{
	Spawn:
		LOOT B 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

class LootSceptre : LootItem
{
	Default
	{
		Inventory.Amount 1500;
		Inventory.PickupMessage "$GOTLOOT3";
	}
	
	States
	{
	Spawn:
		LOOT C 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

class LootBible : LootItem
{
	Default
	{
		Inventory.Amount 2000;
		Inventory.PickupMessage "$GOTLOOT4";
	}
	
	States
	{
	Spawn:
		LOOT D 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

class LootCrown : LootItem
{
	Default
	{
		Inventory.Amount 2500;
		Inventory.PickupMessage "$GOTLOOT5";
	}
	
	States
	{
	Spawn:
		LOOT E 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

class LootCredits : LootItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT7";
		scale 0.8;
	}
	
	States
	{
	Spawn:
		LOOT G 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

// Figurines
// Classic Doom
class LootFigurine1 : LootItem
{
	Default
	{
		Inventory.Amount 6666;
		Inventory.PickupMessage "$GOTLOOTFIG1";
		inventory.pickupsound "items/lootfig";
		scale 0.75;
	}
	
	States
	{
	Spawn:
		LFIG A 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

// Doom 3
class LootFigurine2 : LootFigurine1
{
	Default
	{
		Inventory.PickupMessage "$GOTLOOTFIG2";
	}
	
	States
	{
	Spawn:
		LFIG B 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

// Doom 2016
class LootFigurine3 : LootFigurine1
{
	Default
	{
		Inventory.PickupMessage "$GOTLOOTFIG3";
	}
	
	States
	{
	Spawn:
		LFIG C 0;
		"####" "#" 0;
		goto MoveAround;
	}
}

// Doom 64
class LootFigurine4 : LootFigurine1
{
	Default
	{
		Inventory.PickupMessage "$GOTLOOTFIG4";
	}
	
	States
	{
	Spawn:
		LFIG D 0;
		"####" "#" 0;
		goto MoveAround;
	}
}