/*
----------------------------
MetaDoom
Actor Definitions
Ammunition
----------------------------
*/

// One ugly work around to add item pickup sounds without
// defining new ammo types, coming right up!

class Clip2 : Clip replaces Clip
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIP";
		Inventory.Amount 10;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 400;
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		Inventory.Icon "CLIPA0";
		inventory.pickupsound "items/clip";
	}
	
	States
	{
	Spawn:
		CLIP A -1;
		Stop;
	}
}

// Clip Boxes have a 25% chance of spawning a Dog Collar on spawn.
class ClipBox2 : Clip replaces ClipBox
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIPBOX";
		Inventory.Amount 50;
		inventory.pickupsound "items/clipx";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	mixin LootSpawn;
	
	States
	{
	Spawn:
		AMMO A 0;
		AMMO A 0 A_Jump(64, "SpawnInv");
		goto Chill;
	SpawnInv:
		AMMO A 0 A_Jump(256, "DogCollar");
		goto Chill;
	DogCollar:
		AMMO A 0 A_SpawnLoot("DogCollarPickup");
		goto Chill;
	Chill:
		AMMO A -1;
		Stop;
	}
}

class ClipBox2NoItemSpawn : ClipBox2
{
	Default
	{
		//$Category "Ammunition/MetaDoom"
		//$Title "Clip Box (No Item Spawn Chance)"
		//$NotAngled
		//$Color 6
	}
	
	States
	{
	Spawn:
		AMMO A 0;
		goto Chill;
	}
}

// Rockets have a 33% chance of spawning a Hand Grenade on spawn.
class RocketAmmo2 : RocketAmmo replaces RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKET";
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "ROCKA0";
		inventory.pickupsound "items/rocket";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	mixin LootSpawn;
	
	States
	{
	Spawn:
		ROCK A 0;
		ROCK A 0 A_Jump(86, "SpawnInv");
		goto Chill;
	SpawnInv:
		ROCK A 0 A_Jump(256, "HandGrenade");
		goto Chill;
	HandGrenade:
		ROCK A 0 A_SpawnLoot("HandGrenadePickup");
		goto Chill;
	Chill:
		ROCK A -1;
		Stop;
	}
}

class RocketAmmo2NoItemSpawn : RocketAmmo2
{
	Default
	{
		//$Category "Ammunition/MetaDoom"
		//$Title "Rocket (No Item Spawn Chance)"
		//$NotAngled
		//$Color 6
	}
	States
	{
	Spawn:
		ROCK A 0;
		goto Chill;
	}
}

// Rocket Boxes have a 37% chance of spawning a Hand Grenade on spawn.
class RocketBox2 : RocketAmmo replaces RocketBox
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKBOX";
		Inventory.Amount 5;
		inventory.pickupsound "items/rocketx";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	mixin LootSpawn;
	
	States
	{
	Spawn:
		BROK A 0;
		BROK A 0 A_Jump(96, "SpawnInv");
		goto Chill;
	SpawnInv:
		BROK A 0 A_Jump(256, "HandGrenade");
		goto Chill;
	HandGrenade:
		BROK A 0 A_SpawnLoot("HandGrenadePickup");
		goto Chill;
	Chill:
		BROK A -1;
		Stop;
	}
}

class RocketBox2NoItemSpawn : RocketBox2
{
	Default
	{
		//$Category "Ammunition/MetaDoom"
		//$Title "Rocket Box (No Item Spawn Chance)"
		//$NotAngled
		//$Color 6
	}
	
	States
	{
	Spawn:
		BROK A 0;
		goto Chill;
	}
}

// Cells have a 25% chance of spawning either a Siphon Grenade or a Tesla Rocket.
class Cell2 : Cell replaces Cell
{
	Default
	{
		Inventory.PickupMessage "$GOTCELL";
		Inventory.Amount 20;
		Inventory.MaxAmount 300;
		Ammo.BackpackAmount 20;
		Ammo.BackpackMaxAmount 600;
		Inventory.Icon "CELLA0";
		inventory.pickupsound "items/cell";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	mixin LootSpawn;
	
	States
	{
	Spawn:
		CELL A 0;
		CELL A 0 A_Jump(64, "SpawnInv");
		goto Chill;
	SpawnInv:
		BROK A 0 A_Jump(128, "Siphon");
		BROK A 0 A_Jump(256, "Tesla");
		goto Chill;
	Tesla:
		BROK A 0 A_SpawnLoot("TeslaRocketPickup");
		goto Chill;
	Siphon:
		BROK A 0 A_SpawnLoot("SiphonGrenadePickup");
		goto Chill;
	Chill:
		CELL A -1;
		Stop;
	}
}

class Cell2NoItemSpawn : Cell2
{
	Default
	{
		//$Category "Ammunition/MetaDoom"
		//$Title "Cell (No Item Spawn Chance)"
		//$NotAngled
		//$Color 6
	}
	
	
	States
	{
	Spawn:
		CELL A 0;
		goto Chill;
	}
}

// Cell Packs have a 25% chance of spawning BFG ammo alongside it. If this happens,
// there is an additional 50% chance of a Tesla Rocket also spawning.
class CellPack2 : Cell replaces CellPack
{
	Default
	{
		Inventory.PickupMessage "$GOTCELLBOX";
		Inventory.Amount 100;
		inventory.pickupsound "items/cellx";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	mixin LootSpawn;
	
	States
	{
	Spawn:
		CELP A 0;
		CELP A 0 A_Jump(64, "SpawnInv");
		goto Chill;
	SpawnInv:
		BROK A 0 A_Jump(256, "BFGAmmo");
		goto Chill;
	BFGAmmo:
		BROK A 0 A_SpawnLoot("BFGAmmo");
		BROK A 0 A_Jump(128, "Tesla");
		goto Chill;
	Tesla:
		BROK A 0 A_SpawnLoot("TeslaRocketPickup");
		goto Chill;
	Chill:
		CELP A -1;
		Stop;
	}
}

class CellPack2NoItemSpawn : CellPack2
{
	Default
	{
		//$Category "Ammunition/MetaDoom"
		//$Title "Cell Pack (No Item Spawn Chance)"
		//$NotAngled
		//$Color 6
	}
	
	States
	{
	Spawn:
		CELP A 0;
		goto Chill;
	}
}

class Shell2 : Shell replaces Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLS";
		Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "SHELA0";
		inventory.pickupsound "items/shell";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	States
	{
	Spawn:
		SHEL A -1;
		Stop;
	}
}

class ShellBox2 : Shell replaces ShellBox
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLBOX";
		inventory.pickupsound "items/shellx";
		Inventory.Amount 20;
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	States
	{
	Spawn:
		SBOX A -1;
		Stop;
	}
}

// Backpacks have a 25% chance of spawning a Kinetic Mine.
// We use a seperate class to spawn the backpack, ala the weapons, because otherwise
// the Kinetic Mine-spawning logic would trigger a crash in the Codex screen.
class BackpackSpawner : Actor replaces Backpack
{
	Default
	{
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
	}
	
	mixin LootSpawn;
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(64,"Mines");
		goto Backpack;
	Mines:
		TNT1 A 0 A_SpawnLoot("KineticMinePickup");
		goto Backpack;
	Backpack:
		TNT1 A 0 A_SpawnItemEx("Backpack2",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION);
		stop;
	}
}

class Backpack2 : BackpackItem
{
	Default
	{
		Height 26;
		Inventory.PickupMessage "$GOTBACKPACK";
		inventory.pickupsound "items/pack";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		//$Category "Ammunition/MetaDoom"
		//$Title "Backpack (No Item Spawn Chance)"
		//$NotAngled
		//$Color 6
	}
	
	States
	{
	Spawn:
		BPAK A -1;
		Stop;
	}
}

// New Ammos
class BFGAmmo : Ammo
{
	Default
	{
		Inventory.PickupMessage "$GOTARGENT";
		Inventory.Amount 1;
		Inventory.MaxAmount 10;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 10;
		Inventory.Icon "ARGAA0";
		inventory.pickupsound "items/bfg";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		+BLOCKASPLAYER
		//$Category "Ammunition/MetaDoom"
		//$Title "BFG Core"
		//$NotAngled
		//$Color 6
	}
	
	States
	{
	Spawn:
		ARGA AB 4;
		loop;
	}
}

class SoulAmmo : Ammo
{
	Default
	{
		Inventory.PickupMessage "$GOTSOUL";
		Inventory.Amount 1;
		Inventory.MaxAmount 10;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 10;
		Inventory.Icon "SOLAA0";
		inventory.pickupsound "weapons/soulcube/ammo";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		renderstyle "Add";
		scale 0.5;
		//$Category "Ammunition/MetaDoom"
		//$Title "Soul Ammo"
		//$NotAngled
		//$Color 6
	}
	
	States
	{
	Spawn:
		SOLA ABCB 4 bright;
		loop;
	}
}

// Lazy(?) way of ensuring that souls only spawn 50% of the time when killing enemies.
class SoulSpawner : Actor
{
	Default
	{
		radius 16;
		height 16;
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(CallACS("Item_SoulCube", 0, 0, 0) == 2, "GimmeTheSouls");
		stop;
	GimmeTheSouls:
		TNT1 A 0 A_Jump(128, "NoReallyGiveMeTheSouls");
		stop;
	NoReallyGiveMeTheSouls:
		TNT1 A 0 A_SpawnItemEx("SoulAmmo",0,0,0,random(0,8),random(0,8),8,random(0,360));
		stop;
	}
}