/*
----------------------------
MetaDoom
class Definitions
Keycards and Skull Keys
----------------------------
*/

// The base for these keys was apparently "Borrowed" from Samsara, but I can't
// for the life of me remember how.

class RedCard2 : Key replaces RedCard
{
	Default
	{
	inventory.pickupmessage "$GOTREDCARD";
	inventory.pickupsound "items/keycard";
	TeleFogSourceType "MetaItemFog";
	TeleFogDestType "MetaItemFog";
	species "RedCard";
	+NOTDMATCH
	+DONTGIB
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 2, "Doom3");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 3, "Doom4");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 4, "DoomRPG");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 5, "Doom64");
		goto Doom;
	Doom:
		RKEY A 10;
		RKEY B 10 bright;
		loop;
	Doom3:
		RKEY C 10;
		RKEY D 10 bright;
		loop;
	Doom4:
		RKEY E 10;
		RKEY F 10 bright;
		loop;
	DoomRPG:
		RKEY G 10;
		RKEY H 10 bright;
		loop;
	Doom64:
		RKEY I 10;
		RKEY J 10 bright;
		loop;
	}
}

class YellowCard2 : Key replaces YellowCard
{
	Default
	{
	inventory.pickupmessage "$GOTYELWCARD";
	inventory.pickupsound "items/keycard";
	TeleFogSourceType "MetaItemFog";
	TeleFogDestType "MetaItemFog";
	species "YellowCard";
	+NOTDMATCH
	+DONTGIB
	}
	
	States
	{
	  Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 2, "Doom3");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 3, "Doom4");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 4, "DoomRPG");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 5, "Doom64");
		goto Doom;
	Doom:
		YKEY A 10;
		YKEY B 10 bright;
		loop;
	Doom3:
		YKEY C 10;
		YKEY D 10 bright;
		loop;
	Doom4:
		YKEY E 10;
		YKEY F 10 bright;
		loop;
	DoomRPG:
		YKEY G 10;
		YKEY H 10 bright;
		loop;
	Doom64:
		YKEY I 10;
		YKEY J 10 bright;
		loop;
	}
}

class BlueCard2 : Key replaces BlueCard
{
	Default
	{
	inventory.pickupmessage "$GOTBLUECARD";
	inventory.pickupsound "items/keycard";
	TeleFogSourceType "MetaItemFog";
	TeleFogDestType "MetaItemFog";
	species "BlueCard";
	+NOTDMATCH
	+DONTGIB
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 2, "Doom3");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 3, "Doom4");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 4, "DoomRPG");
		TNT1 A 0 A_JumpIf(CallACS("Key_ReturnType", 0, 0, 0) == 5, "Doom64");
		goto Doom;
	Doom:
		BKEY A 10;
		BKEY B 10 bright;
		loop;
	Doom3:
		BKEY C 10;
		BKEY D 10 bright;
		loop;
	Doom4:
		BKEY E 10;
		BKEY F 10 bright;
		loop;
	DoomRPG:
		BKEY G 10;
		BKEY H 10 bright;
		loop;
	Doom64:
		BKEY I 10;
		BKEY J 10 bright;
		loop;
	}
}

class RedSkull2 : Key replaces RedSkull
{
	Default
	{
	inventory.pickupmessage "$GOTREDSKUL";
	inventory.pickupsound "items/keyskull";
	TeleFogSourceType "MetaItemFog";
	TeleFogDestType "MetaItemFog";
	species "RedSkull";
	+NOTDMATCH
	+DONTGIB
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(CallACS("SkullKey_ReturnType", 0, 0, 0) == 2, "Doom64");
		TNT1 A 0 A_JumpIf(CallACS("SkullKey_ReturnType", 0, 0, 0) == 3, "Doom4");
		goto Doom;
	Doom:
		RSKU A 10;
		RSKU B 10 bright;
		loop;
	Doom64:
		RSKU C 10;
		RSKU D 10 bright;
		loop;
	Doom4:
		TNT1 A 0 A_SetScale(0.62);
		KSKR ABCDDDCBAA 4 Bright;
		Loop;
	}
}

class YellowSkull2 : Key replaces YellowSkull
{
	Default
	{
	inventory.pickupmessage "$GOTYELWSKUL";
	inventory.pickupsound "items/keyskull";
	TeleFogSourceType "MetaItemFog";
	TeleFogDestType "MetaItemFog";
	species "YellowSkull";
	+NOTDMATCH
	+DONTGIB
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(CallACS("SkullKey_ReturnType", 0, 0, 0) == 2, "Doom64");
		TNT1 A 0 A_JumpIf(CallACS("SkullKey_ReturnType", 0, 0, 0) == 3, "Doom4");
		goto Doom;
	Doom:
		YSKU A 10;
		YSKU B 10 bright;
		loop;
	Doom64:
		YSKU C 10;
		YSKU D 10 bright;
		loop;
	Doom4:
		TNT1 A 0 A_SetScale(0.62);
		KSKY ABCDDDCBAA 3 Bright;
		Loop;
	}
}

class BlueSkull2 : Key replaces BlueSkull
{
	Default
	{
	inventory.pickupmessage "$GOTBLUESKUL";
	inventory.pickupsound "items/keyskull";
	TeleFogSourceType "MetaItemFog";
	TeleFogDestType "MetaItemFog";
	species "BlueSkull";
	+NOTDMATCH
	+DONTGIB
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(CallACS("SkullKey_ReturnType", 0, 0, 0) == 2, "Doom64");
		TNT1 A 0 A_JumpIf(CallACS("SkullKey_ReturnType", 0, 0, 0) == 3, "Doom4");
		goto Doom;
	Doom:
		BSKU A 10;
		BSKU B 10 bright;
		loop;
	Doom64:
		BSKU C 10;
		BSKU D 10 bright;
		loop;
	Doom4:
		TNT1 A 0 A_SetScale(0.62);
		KSKB ABCDDDCBAA 3 Bright;
		Loop;
	}
}