/*
----------------------------
MetaDoom
Actor Definitions
Score Items
----------------------------
*/

// Pointless but fun, these items do nothing but look nice and increase your score.

// 25% chance of spawning a low-scoring item
// 12.5% chance of spawning a high-scoring item
// Figurines have been moved to metaloreitems.zsc
class LootSpawner : Actor
{
	Default
	{
		radius 64;
		height 32;
	}
	
	mixin LootSpawn;
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			ThinkerIterator it = ThinkerIterator.Create("MetaDoomMapID");
			Actor mo;
			while (mo = MetaDoomMapID(it.Next()))
			{
				if (meta_developer)
					Console.printf("Loot: This is a MetaDoom map, no loot spawning!");
				self.A_Remove(AAPTR_DEFAULT, RMVF_EVERYTHING);
			}
		}
		TNT1 A 0 A_Jump(64, "Loot1", "Loot2", "Loot6", "Loot7");
		TNT1 A 0 A_Jump(32, "Loot3", "Loot4", "Loot5");
		stop;
	Loot1:
		TNT1 A 0 A_SpawnLoot("LootDagger"); //A_SpawnItemEx("LootDagger",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot2:
		TNT1 A 0 A_SpawnLoot("LootChest"); //A_SpawnItemEx("LootChest",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot3:
		TNT1 A 0 A_SpawnLoot("LootSceptre"); //A_SpawnItemEx("LootSceptre",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot4:
		TNT1 A 0 A_SpawnLoot("LootBible"); //A_SpawnItemEx("LootBible",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot5:
		TNT1 A 0 A_SpawnLoot("LootCrown"); //A_SpawnItemEx("LootCrown",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot6:
		TNT1 A 0 A_SpawnLoot("LootGoblet"); //A_SpawnItemEx("LootGoblet",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	Loot7:
		TNT1 A 0 A_SpawnLoot("LootCredits"); //A_SpawnItemEx("LootCredits",0,0,0,random(1,16),random(1,16),0,random(0,360));
		stop;
	}
	
}

class LootItem : ScoreItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT6";
		inventory.pickupsound "items/loot";
		BounceType "Grenade";
		Bouncefactor 0.0;
		WallBouncefactor 1.0;
		-COUNTITEM
		+BLOCKASPLAYER
	}
	
	States
	{
	Spawn:
		LOOT F 0;
		"####" "#" 0;
		goto Sit;
	Sit:
		"####" "#" -1;
		loop;
	}
}

class LootGoblet : LootItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT6";
		//$Category "MetaDoom Loot"
		//$Title "Goblet (500pt)"
		//$NotAngled
		//$Color 19
	}
	
	States
	{
	Spawn:
		LOOT F 0;
		"####" "#" 0;
		goto Sit;
	}
}

class LootDagger : LootItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT1";
		//$Category "MetaDoom Loot"
		//$Title "Dagger (500pt)"
		//$NotAngled
		//$Color 19
	}
	
	States
	{
	Spawn:
		LOOT A 0;
		"####" "#" 0;
		goto Sit;
	}
}

class LootChest : LootItem
{
	Default
	{
		Inventory.Amount 1000;
		Inventory.PickupMessage "$GOTLOOT2";
		//$Category "MetaDoom Loot"
		//$Title "Chest (1000pt)"
		//$NotAngled
		//$Color 19
	}
	
	States
	{
	Spawn:
		LOOT B 0;
		"####" "#" 0;
		goto Sit;
	}
}

class LootSceptre : LootItem
{
	Default
	{
		Inventory.Amount 1500;
		Inventory.PickupMessage "$GOTLOOT3";
		//$Category "MetaDoom Loot"
		//$Title "Sceptre (1500pt)"
		//$NotAngled
		//$Color 19
	}
	
	States
	{
	Spawn:
		LOOT C 0;
		"####" "#" 0;
		goto Sit;
	}
}

class LootBible : LootItem
{
	Default
	{
		Inventory.Amount 2000;
		Inventory.PickupMessage "$GOTLOOT4";
		//$Category "MetaDoom Loot"
		//$Title "Unholy Bible (2000pt)"
		//$NotAngled
		//$Color 19
	}
	
	States
	{
	Spawn:
		LOOT D 0;
		"####" "#" 0;
		goto Sit;
	}
}

class LootCrown : LootItem
{
	Default
	{
		Inventory.Amount 2500;
		Inventory.PickupMessage "$GOTLOOT5";
		//$Category "MetaDoom Loot"
		//$Title "Crown (2500pt)"
		//$NotAngled
		//$Color 19
	}
	
	States
	{
	Spawn:
		LOOT E 0;
		"####" "#" 0;
		goto Sit;
	}
}

class LootCredits : LootItem
{
	Default
	{
		Inventory.Amount 500;
		Inventory.PickupMessage "$GOTLOOT7";
		scale 0.8;
		//$Category "MetaDoom Loot"
		//$Title "UAC Credits (500pt)"
		//$NotAngled
		//$Color 19
	}
	
	States
	{
	Spawn:
		LOOT G 0;
		"####" "#" 0;
		goto Sit;
	}
}

