/*
----------------------------
MetaDoom
Actor Definitions
Gibbage!
----------------------------
*/

class MetaGibber : Actor
{
	Default
	{
	radius 20;
	height 56;
	+NOCLIP
	}
	
	states
	{
	Spawn:
	    TNT1 A 0;
	    TNT1 A 0 A_PlaySound("gibbage/gib");
		TNT1 A 0
		{
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2, random (0, 160));
			}
			
			A_SpawnItem("BloodSplat");
		}
	    TNT1 A 1 A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 1 A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 1 A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    TNT1 A 0 A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
	    Stop;
	}
}

// Unidentifiable bloody GOOSH
class MetaSploosh : Actor // edited version of smoothdoom gib1
{
	Default
	{
	Radius 3;
	Height 3;
	Speed 7;
	Scale 1.0;
	Mass 1;
	+NOBLOCKMAP
	+MISSILE
	+NOTELEPORT
	+MOVEWITHSECTOR
	+CLIENTSIDEONLY
	+BLOODLESSIMPACT 
	+DONTSPLASH
	+FLOORCLIP
	Decal "Bloodsmear";
	Gravity 0.7;
	}
	
	States
	{
	Spawn:
		GIBS C 3;
	    Loop;
	Death:
	    TNT1 A 0 A_JumpIf(waterlevel == 2,"Disappear");
		TNT1 A 0 A_PlaySound("effects/blood");
		TNT1 A 0 A_SpawnItem("BloodSplat");
	    Stop;
	Disappear:
		TNT1 A 1;
		stop;
	}
}

class MetaSplooshBlue : MetaSploosh
{
	Default
	{
	decal "bluebloodsmear";
	translation "32:47=240:243", "176:191=199:207";
	}
	
	States
	{
	Death:
	    TNT1 A 0 A_JumpIf(waterlevel == 2,"Disappear");
		TNT1 A 0 A_PlaySound("effects/blood");
		TNT1 A 0 A_SpawnItem("BloodSplatBlue");
	    Stop;
	}
}

class MetaSplooshGreen : MetaSploosh
{
	Default
	{
	decal "greenbloodsmear";
	translation "176:191=112:127", "32:47=112:127", "160:167=112:127";
	}
	
	States
	{
	Death:
	    TNT1 A 0 A_JumpIf(waterlevel == 2,"Disappear");
		TNT1 A 0 A_PlaySound("effects/blood");
		TNT1 A 0 A_SpawnItem("BloodSplatGreen");
	    Stop;
	}
}

// Individual Unique Gib Actors
// These abuse ROLLSPRITE because it was new and nobody else was.
class MetaGib1 : Actor
{
	Default
	{
	+DOOMBOUNCE
	PROJECTILE;
	-NOGRAVITY
	//-NOBLOCKMAP
	-ACTIVATEIMPACT
	+NOTELEPORT
	-TELESTOMP
	-SOLID
	+ROLLSPRITE
	+ROLLCENTER
	Radius 2;
	Damage 0;
	Decal "BloodSplat";
	bouncefactor 0.5;
	SeeSound "gibbage/gibphys";
	gravity 0.5;
	Speed 5;
	scale 0.75;
	}
	
	int user_lifetime;
	
	States
	{
	Spawn:
		JIBS A 0;
		goto Setup;
	Setup:
		"####" # 0 ThrustThingZ (0, random(32,45), 0, 1);
		"####" # 0 A_SetRoll(random(0,360));
		"####" # 0 { user_lifetime = 0; }
	ChangeDir:
		"####" # 0 A_Jump(128,"Alt");
		goto See;
	See:
		"####" # 0 A_SpawnItem("FlyingBloodCheap");
		"####" # 0 ThrustThingZ(0,6,1,1);
		"####" # 1 A_SetRoll((roll + 5));
		loop;
	Alt:
		"####" # 0 A_SpawnItem("FlyingBloodCheap");
		"####" # 0 ThrustThingZ(0,6,1,1);
		"####" # 1 A_SetRoll((roll - 5));
		loop;
	Bounce.Floor:
		//"####" # 0 A_SpawnItem("BloodSplat")
		goto ChangeDir;
	Bounce.Wall:
		goto ChangeDir;
	Death:
		"####" # 0 A_ChangeLinkFlags(true); //A_ChangeFlag(NOBLOCKMAP, 0);
	EternalRest:
		"####" # 35 { user_lifetime += 35; }
		"####" # 1 A_JumpIf((user_lifetime >= meta_perf_bloodtime), "FadeMeOut");
		loop;
	FadeMeOut:
		"####" "#" 1 A_FadeOut(0.02);
		Wait;
	}
}

class MetaGib2 : MetaGib1
{
	States
	{
	Spawn:
		JIBS B 0;
		goto Setup;
	}
}

class MetaGib3 : MetaGib1
{
	States
	{
	Spawn:
		JIBS C 0;
		goto Setup;
	}
}

class MetaGib4 : MetaGib1
{
	States
	{
	Spawn:
		JIBS D 0;
		goto Setup;
	}
}

class MetaGib5 : MetaGib1
{
	States
	{
	Spawn:
		JIBS E 0;
		goto Setup;
	}
}

class MetaGib6 : MetaGib1
{
	States
	{
	Spawn:
		JIBS F 0;
		goto Setup;
	}
}

class MetaGib7 : MetaGib1
{
	States
	{
	Spawn:
		JIBS G 0;
		goto Setup;
	}
}

class MetaGib8 : MetaGib1
{
	States
	{
	Spawn:
		JIBS H 0;
		goto Setup;
	}
}

class MetaGib9 : MetaGib1
{
	States
	{
	Spawn:
		JIBS I 0;
		goto Setup;
	}
}

class MetaGib10 : MetaGib1
{
	States
	{
	Spawn:
		JIBS J 0;
		goto Setup;
	}
}

class MetaGib11 : MetaGib1
{
	States
	{
	Spawn:
		JIBS K 0;
		goto Setup;
	}
}

class MetaGib12 : MetaGib1
{
	States
	{
	Spawn:
		JIBS L 0;
		goto Setup;
	}
}