/*
----------------------------
MetaDoom
Actor Definitions
Core Actors
----------------------------
*/

// Horrible remains of the pre-ZScript era. Legacy codebases, eh?

class _Boolean : Inventory
{
    Default
	{
	Inventory.MaxAmount 1;
    +Inventory.UNDROPPABLE
    -Inventory.INVBAR
	}
}

class Counter : Inventory
{
    Default
	{    
	Inventory.MaxAmount 0x7FFFFFFF;
    +Inventory.UNDROPPABLE
    -Inventory.INVBAR
	}
}

// For level designers to tell scripts that it's a MetaDoom map.
class MetaDoomMapID : Actor
{
	Default
	{
		Radius 32;
		Height 56;
		+NOGRAVITY
		-SOLID
		+DONTSPLASH
		+INVISIBLE
		//$Category "Editor Things"
		//$Title "This Is A MetaDoom Map!"
		//$NotAngled
	}
	States
	{
	Spawn:
		EDIT A -1;
		Stop;
	}
}