/*
----------------------------
MetaDoom
Actor Definitions
Chainsaw
----------------------------
*/

class MetaChainsawPickup : WeaponGiver
{
	Default
	{
		DropItem "MetaChainsaw";
		Inventory.PickupMessage "$GOTCHAINSAW";
		Inventory.PickupSound "weapons/chainsaw/get";
	}
	
	States
	{
	Spawn:
		WSAW Z 0;
		WSAW Z 0 { bDROPPED = 0; }
		WSAW Z -1;
		Stop;
	}
}

class MetaChainsaw : MetaDoomWeapon
{
	Default
	{
		Weapon.Kickback 0;
		Weapon.SelectionOrder 2300;
		Weapon.UpSound "weapons/sawup";
		//Weapon.ReadySound "weapons/sawidle"
		Inventory.PickupMessage "$GOTCHAINSAW";
		Obituary "$OB_METACHAINSAW";
		Tag "$TAG_CHAINSAW";
		+WEAPON.MELEEWEAPON		
		Inventory.PickupSound "weapons/chainsaw/get";
		Weapon.YAdjust 10;
		//$Category "Weapons/MetaDoom"
		//$Title "Chainsaw"
		//$NotAngled
		//$Color 14
	}
	
	States
	{
	Ready:
		WSAW A 0 A_PlaySound ("weapons/chainsaw/idle", CHAN_WEAPON, 1.0, 1);
		WSAW A 1 Offset(0,32) A_WeaponReady(WRF_NOBOB);
		WSAW A 0 A_JumpIfInventory("MeleePunch", 1, "Melee");
		WSAW B 1 Offset(1,33) A_WeaponReady(WRF_NOBOB);
		WSAW B 0 A_JumpIfInventory("MeleePunch", 1, "Melee");
		WSAW A 1 Offset(0,31) A_WeaponReady(WRF_NOBOB);
		WSAW A 0 A_JumpIfInventory("MeleePunch", 1, "Melee");
		WSAW B 1 Offset(-1,33) A_WeaponReady(WRF_NOBOB);
		WSAW B 0 A_JumpIfInventory("MeleePunch", 1, "Melee");	
		Loop;
	Deselect:
		WSAW A 0;
		WSAW A 0 A_JumpIf(health <= 0, "DeadDude");
		WSAW A 0 A_PlaySound("weapons/chainsaw/off", CHAN_WEAPON);
	FinishDeselect:
		WSAW A 1 A_SmoothLower();
		Loop;
	Select:
		WSAW A 0 A_PlaySound("weapons/chainsaw/use", CHAN_WEAPON);
	FinishSelect:
		WSAW AB 1 A_SmoothRaise();
		loop;
	Fire:
		WSAW C 0 
		{
			A_PlaySound ("weapons/chainsaw/attack", CHAN_WEAPON, 1.0, 1);
			
			if (CountInv("PowerDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
		}
		WSAW C 1 Offset(0,32) A_Saw ("null","weapons/chainsaw/attackhit");
		WSAW D 1 Offset(1,30);
		WSAW C 1 Offset(-1,34);
		WSAW D 1 Offset(0,31);
		WSAW C 0 A_ReFire;
		Goto Ready;
	AltFire:
		WSAW A 1 Offset(0,35);
		WSAW B 1 Offset(0,37);
		WSAW A 1 Offset(0,40);
		WSAW B 1 Offset(0,50);
		WSAW A 3 Offset(0,60);
		TNT1 A 0 Offset(0,32);
		WSAW E 0 A_StopSound(CHAN_WEAPON);
		WSAW H 1 
		{
			A_PlaySound ("weapons/chainsaw/slash", CHAN_BODY);
			
			if (CountInv("PowerDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
		}
		WSAW I 1;
		WSAW J 1 A_FireProjectile("ChainsawSlash", -32, 0, 0, 0, FPF_NOAUTOAIM);
		WSAW K 1 A_FireProjectile("ChainsawSlash", -16, 0, 0, 0, FPF_NOAUTOAIM);
		WSAW L 1 A_FireProjectile("ChainsawSlash", 0, 0, 0, 0, FPF_NOAUTOAIM);
		WSAW M 1 A_FireProjectile("ChainsawSlash", 16, 0, 0, 0, FPF_NOAUTOAIM);
		WSAW N 1 A_FireProjectile("ChainsawSlash", 32, 0, 0, 0, FPF_NOAUTOAIM);
		TNT1 A 1 Offset(-1,90);
		TNT1 A 32 Offset(0,90);
		WSAW A 1 Offset(0,90) A_PlaySound("weapons/chainsaw/get", CHAN_WEAPON);
		WSAW B 1 Offset(0,80);
		WSAW A 1 Offset(0,70);
		WSAW B 1 Offset(0,60);
		WSAW A 1 Offset(0,55);
		WSAW B 1 Offset(0,49);
		WSAW A 1 Offset(0,44);
		WSAW B 1 Offset(0,39);
		WSAW A 1 Offset(0,35);
		WSAW B 1 Offset(0,33);
		WSAW A 1 Offset(0,32);
		goto Ready;
	Melee:
		WSAW A 1 Offset(0,35);
		WSAW B 1 Offset(0,47);
		WSAW A 1 Offset(0,55);
		WSAW B 1 Offset(0,70);
		WSAW A 3 Offset(0,80);
		WSAW E 0 A_StopSound(CHAN_WEAPON);
		WSAW E 1 Offset(1,65)
		{
			A_PlaySound ("weapons/chainsaw/slash", CHAN_BODY);
			
			if (CountInv("PowerDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
		}
		WSAW F 1 Offset(0,42) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW E 1 Offset(-1,30) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW F 1 Offset(0,28) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW E 1 Offset(1,26) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW E 1 Offset(-1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW E 1 Offset(1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW E 1 Offset(-1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW E 1 Offset(1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW E 1 Offset(-1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		WSAW F 1 Offset(0,26);
		WSAW A 1 Offset(0,28);
		WSAW A 1 Offset(0,32);
		WSAW A 1 Offset(0,35);
		WSAW A 1 Offset(0,39);
		WSAW A 1 Offset(0,49);
		WSAW A 1 Offset(0,60);
		WSAW A 1 Offset(0,80);
		TNT1 A 5;
		WSAW A 1 Offset(0,90) A_PlaySound("weapons/chainsaw/get", CHAN_WEAPON);
		WSAW B 1 Offset(0,80);
		WSAW A 1 Offset(0,70);
		WSAW B 1 Offset(0,60);
		WSAW A 1 Offset(0,55);
		WSAW B 1 Offset(0,49);
		WSAW A 1 Offset(0,44);
		WSAW B 1 Offset(0,39);
		WSAW A 1 Offset(0,35);
		WSAW B 1 Offset(0,33);
		WSAW A 1 Offset(0,32);
		goto Ready;
	Spawn:
		WSAW Z -1;
		Stop;
	}
}

class ChainsawSlash : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 10;
		DamageFunction (3 * random(1, 4));
		Projectile;
		+RIPPER
		Obituary "$OB_METACHAINSAW_SLASH";
		alpha 0.5;
	}
	
	States
	{
	Spawn:
		CSLS A 8;
		stop;
	Death:
		TNT1 A 0;
		Stop;
	}
}

class MetaChainsawMeleePuff : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		damagetype "ChainsawMelee";
		RenderStyle "Translucent";
		Alpha 0.5;
		VSpeed 1;
		Mass 5;
		//AttackSound "weapons/melee/hitwall"
		SeeSound "weapons/melee/hit";
		Obituary "$OB_METAFIST";
	}
	States
	{
	Spawn:
		PUFF A 4 Bright;
		PUFF B 4;
	Melee:
		PUFF CD 4;
		Stop;
	}
}