/*
----------------------------
MetaDoom
Actor Definitions
Soulcube
----------------------------
*/

class SoulCubeUsed : _Boolean {}
class SoulCubeMessagePopped : _Boolean {}

class MetaSoulcubePickup : WeaponGiver
{
	Default
	{
		DropItem "MetaSoulcube";
		Inventory.Pickupmessage "$GOTSOULCUBE";
		Inventory.PickupSound "weapons/soulcube/get";
		+FLOATBOB;
	}
	
	States
	{
	Spawn:
		SOLP Z 0;
		SOLP Z 0 { bDROPPED = 0; }
	Animation:
		SOLP XYZY 10 bright;
		loop;
	}
}

class MetaSoulcube : MetaDoomWeapon
{
	Default
	{
		Weapon.SelectionOrder 2900;
		Obituary "$OB_METASOULCUBE";
		Weapon.AmmoUse1 10;
		Weapon.AmmoType1 "SoulAmmo";
		Weapon.AmmoUse2 10;
		Weapon.AmmoType2 "SoulAmmo";
		Inventory.Pickupmessage "$GOTSOULCUBE";
		Inventory.PickupSound "weapons/soulcube/get";
		Tag "$TAGSOULCUBE";
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.UNTOSSABLE
		+FLOATBOB
		Weapon.UpSound "weapons/soulcube/use";
		Weapon.SlotNumber 7;
		//$Category "Weapons/MetaDoom"
		//$Title "Soul Cube"
		//$NotAngled
		//$Color 14
	}
	
	States
	{
	Ready:
		SOLH A 1 
		{
			A_WeaponReady();
			return A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		}
		Loop;
	Deselect:
		SOLH A 0;
		SOLH A 0 A_JumpIf(health <= 0, "DeadDude");
		SOLH A 0 A_JumpIfInventory("SoulCubeUsed", 1, "OldFinishDeselect");
		SOLH A 0 A_PlaySound("weapons/swap");
	FinishDeselect:
		SOLH A 1 A_SmoothLower();
		Loop;
	Select:
		SOLH A 0
		{
			A_Overlay(2, "Overlay.SoulcubeIdle");
			A_Overlay(3, "Overlay.SoulcubeAnim");
			A_OverlayFlags (2, PSPF_ADDBOB, 0);
			A_OverlayScale(PSP_WEAPON, 1, 1);
		}
	FinishSelect:
		SOLH A 1 A_SmoothRaise();
		loop;
	OldFinishDeselect:
		SOLH A 0 A_TakeInventory("SoulCubeUsed", 9999);
		SOLH A 0 A_Lower;
		Loop;
	AltFire:
	Fire:
		SOLW A 0 A_ClearOverlays();
		SOLW A 4;
		SOLW B 3 bright A_PlaySound("weapons/soulcube/fire", CHAN_WEAPON);
		SOLW CDE 3;
		SOLW E 2 Offset(0,35);
		SOLW E 2 Offset(0,45);
		SOLW E 2 Offset(0,65);
		SOLW E 2 Offset(0,85);
		TNT1 A 2 Offset(0,85) A_FireProjectile("MetaSoulCubeProj", 0, 1, 0, -16);
		TNT1 A 0 Offset(0,32);
		TNT1 A 0 A_GiveInventory("SoulCubeUsed", 1);
		TNT1 A 0 A_SelectWeapon ("MetaUnmaker",  SWF_SELECTPRIORITY); // not the grossest hack, but, you know, up there
		Goto Ready;
	Flash:
		TNT1 A 4 Bright A_Light1;
		Goto LightDone;
		TNT1 A 4 Bright A_Light1;
		Goto LightDone;
 	Spawn:
		SOLP XYZY 10 bright;
		loop;
		
	Overlay.SoulcubeIdle:
		//SOLC ABAC 10;
		SOLC A 0 A_OverlayPivotAlign(2, PSPA_CENTER, PSPA_CENTER);
		SOLC A 2 A_OverlayRotate(2, 5, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, 4, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, 3, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, 2, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, 1, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 5;
		SOLC A 2 A_OverlayRotate(2, -1, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -2, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -3, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -4, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -5, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -4, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -3, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -2, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, -1, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 5;
		SOLC A 2 A_OverlayRotate(2, 1, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, 2, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, 3, WOF_ADD|WOF_INTERPOLATE);
		SOLC A 2 A_OverlayRotate(2, 4, WOF_ADD|WOF_INTERPOLATE);
		loop;
		
	Overlay.SoulcubeAnim:
		TNT1 A 1 A_OverlayOffset(2,0,12,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,14,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,16,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,17,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,18,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,18.2,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,18.4,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,18.6,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,18.4,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,18.2,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,17,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,16,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,14,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,12,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,10,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,8,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,6,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,5,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,4,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,3.8,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,3.6,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,3.4,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,3.6,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,3.8,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,4,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,5,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,6,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,8,WOF_INTERPOLATE);
		TNT1 A 1 A_OverlayOffset(2,0,10,WOF_INTERPOLATE);
		loop;
	}
}

class MetaSoulCubeProj : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 35;
		DamageFunction (1000);
		damagetype "SoulCube";
		Projectile;
		+RANDOMIZE
		+FLATSPRITE
		+ROLLSPRITE
		+ROLLCENTER
		+SEEKERMISSILE
		+SCREENSEEKER
		RenderStyle "Add";
		Alpha 1;
		Obituary "$OB_METASOULCUBE";
		scale 0.5;
		Decal "PlasmaScorch";
	}
	
	States
	{
	Spawn:
		SOLP A 0 A_PlaySound ("weapons/soulcube/loop", CHAN_BODY, 1.0, 1);
		SOLP A 0 A_SeekerMissile(0, 90);
		SOLP A 0 A_SpawnItem("SoulCubeTrail1");
		SOLP A 0 A_SpawnItem("SoulCubeTrail2");
		SOLP A 1 Bright
		{
			A_SetRoll(roll + 15);
			A_SetPitch(pitch + 15);
		}
		Loop;
	Death:
	Crash:
		TNT1 A 0 A_PlaySound("weapons/soulcube/end");
		TNT1 A 0;
		Stop;
	XDeath:
		TNT1 A 0 A_PlaySound("weapons/soulcube/kill");
		TNT1 A 0;
		Stop;
	}
}

class SoulCubeTrail1 : Actor
{
	Default
	{
		+NOINTERACTION
		+NOGRAVITY
		RenderStyle "Add";
		Alpha 1;
		scale 0.5;
	}
	
	states
	{
	Spawn:
		SOLT A 2 A_FadeOut;
	Finalize:
		SOLT A 2 A_FadeOut;
		loop;
	}
}
class SoulCubeTrail2 : Actor
{
	Default
	{
		+NOINTERACTION
		+NOGRAVITY
		+FLATSPRITE
		RenderStyle "Add";
		Alpha 1;
	}
	
	states
	{
	Spawn:
		APBX B 2 A_FadeOut;
	Finalize:
		APBX B 2 A_FadeOut;
		loop;
	}
}