/*
----------------------------
MetaDoom
Actor Definitions
Chainsaw
----------------------------
*/

class MetaChainsawPickup : WeaponGiver
{
	Default
	{
		DropItem "MetaChainsaw";
		Inventory.PickupMessage "$GOTCHAINSAW";
		Inventory.PickupSound "weapons/chainsaw/get";
	}
	
	States
	{
	Spawn:
		CSAW Z 0;
		CSAW Z 0 { bDROPPED = 0; }
		CSAW Z -1;
		Stop;
	}
}

class MetaChainsaw : MetaDoomWeapon
{
	Default
	{
		Weapon.Kickback 0;
		Weapon.SelectionOrder 2300;
		Weapon.UpSound "weapons/sawup";
		//Weapon.ReadySound "weapons/sawidle"
		Inventory.PickupMessage "$GOTCHAINSAW";
		Obituary "$OB_METACHAINSAW";
		Tag "$TAG_CHAINSAW";
		+WEAPON.MELEEWEAPON		
		Inventory.PickupSound "weapons/chainsaw/get";
		Weapon.YAdjust 10;
	}
	
	States
	{
	Ready:
		CSAW A 0 A_PlaySound ("weapons/chainsaw/idle", CHAN_WEAPON, 1.0, 1);
		CSAW A 1 Offset(0,32) A_WeaponReady(WRF_NOBOB);
		CSAW A 0 A_JumpIfInventory("MeleePunch", 1, "Melee");
		CSAW B 1 Offset(1,33) A_WeaponReady(WRF_NOBOB);
		CSAW B 0 A_JumpIfInventory("MeleePunch", 1, "Melee");
		CSAW A 1 Offset(0,31) A_WeaponReady(WRF_NOBOB);
		CSAW A 0 A_JumpIfInventory("MeleePunch", 1, "Melee");
		CSAW B 1 Offset(-1,33) A_WeaponReady(WRF_NOBOB);
		CSAW B 0 A_JumpIfInventory("MeleePunch", 1, "Melee");	
		Loop;
	Deselect:
		CSAW A 1;
		CSAW A 0 A_JumpIf(health <= 0, "DeadDude");
		CSAW A 1 Offset(0,33) A_PlaySound("weapons/chainsaw/off", CHAN_WEAPON);
		CSAW A 1 Offset(0,35);
		CSAW A 1 Offset(0,39);
		CSAW A 1 Offset(0,44);
		CSAW A 1 Offset(0,49);
		CSAW A 1 Offset(0,55);
		CSAW A 1 Offset(0,60);
		CSAW A 1 Offset(0,70);
		CSAW A 1 Offset(0,80);
		CSAW A 1 Offset(0,90);
	FinishDeselect:
		CSAW A 0 A_Lower;
		Loop;
	Select:
		CSAW A 1 Offset(0,90) A_PlaySound("weapons/chainsaw/use", CHAN_WEAPON);
		CSAW B 1 Offset(0,80);
		CSAW A 1 Offset(0,70);
		CSAW B 1 Offset(0,60);
		CSAW A 1 Offset(0,55);
		CSAW B 1 Offset(0,49);
		CSAW A 1 Offset(0,44);
		CSAW B 1 Offset(0,39);
		CSAW A 1 Offset(0,35);
		CSAW B 1 Offset(0,33);
		CSAW A 1 Offset(0,32);
		goto Ready;
	Fire:
		CSAW C 0 
		{
			A_PlaySound ("weapons/chainsaw/attack", CHAN_WEAPON, 1.0, 1);
			
			if (CountInv("PowerDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
		}
		CSAW C 1 Offset(0,32) A_Saw ("null","weapons/chainsaw/attackhit");
		CSAW D 1 Offset(1,30);
		CSAW C 1 Offset(-1,34);
		CSAW D 1 Offset(0,31);
		CSAW C 0 A_ReFire;
		Goto Ready;
	AltFire:
		CSAW A 1 Offset(0,35);
		CSAW B 1 Offset(0,37);
		CSAW A 1 Offset(0,40);
		CSAW B 1 Offset(0,50);
		CSAW A 3 Offset(0,60);
		TNT1 A 0 Offset(0,32);
		CSAW E 0 A_StopSound(CHAN_WEAPON);
		CSAW H 1 
		{
			A_PlaySound ("weapons/chainsaw/slash", CHAN_BODY);
			
			if (CountInv("PowerDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
		}
		CSAW I 1;
		CSAW J 1 A_FireProjectile("ChainsawSlash", -32, 0, 0, 0, FPF_NOAUTOAIM);
		CSAW K 1 A_FireProjectile("ChainsawSlash", -16, 0, 0, 0, FPF_NOAUTOAIM);
		CSAW L 1 A_FireProjectile("ChainsawSlash", 0, 0, 0, 0, FPF_NOAUTOAIM);
		CSAW M 1 A_FireProjectile("ChainsawSlash", 16, 0, 0, 0, FPF_NOAUTOAIM);
		CSAW N 1 A_FireProjectile("ChainsawSlash", 32, 0, 0, 0, FPF_NOAUTOAIM);
		TNT1 A 1 Offset(-1,90);
		TNT1 A 32 Offset(0,90);
		CSAW A 1 Offset(0,90) A_PlaySound("weapons/chainsaw/get", CHAN_WEAPON);
		CSAW B 1 Offset(0,80);
		CSAW A 1 Offset(0,70);
		CSAW B 1 Offset(0,60);
		CSAW A 1 Offset(0,55);
		CSAW B 1 Offset(0,49);
		CSAW A 1 Offset(0,44);
		CSAW B 1 Offset(0,39);
		CSAW A 1 Offset(0,35);
		CSAW B 1 Offset(0,33);
		CSAW A 1 Offset(0,32);
		goto Ready;
	Melee:
		CSAW A 1 Offset(0,35);
		CSAW B 1 Offset(0,47);
		CSAW A 1 Offset(0,55);
		CSAW B 1 Offset(0,70);
		CSAW A 3 Offset(0,80);
		CSAW E 0 A_StopSound(CHAN_WEAPON);
		CSAW E 1 Offset(1,65)
		{
			A_PlaySound ("weapons/chainsaw/slash", CHAN_BODY);
			
			if (CountInv("PowerDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
		}
		CSAW F 1 Offset(0,42) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW E 1 Offset(-1,30) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW F 1 Offset(0,28) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW E 1 Offset(1,26) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW E 1 Offset(-1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW E 1 Offset(1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW E 1 Offset(-1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW E 1 Offset(1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW F 1 Offset(0,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW E 1 Offset(-1,25) A_CustomPunch(5 * random(1, 5), TRUE, CPF_NOTURN,"MetaChainsawMeleePuff",80,0,0,"BasicArmorBonus","weapons/chainsaw/slashhit");
		CSAW F 1 Offset(0,26);
		CSAW A 1 Offset(0,28);
		CSAW A 1 Offset(0,32);
		CSAW A 1 Offset(0,35);
		CSAW A 1 Offset(0,39);
		CSAW A 1 Offset(0,49);
		CSAW A 1 Offset(0,60);
		CSAW A 1 Offset(0,80);
		TNT1 A 5;
		CSAW A 1 Offset(0,90) A_PlaySound("weapons/chainsaw/get", CHAN_WEAPON);
		CSAW B 1 Offset(0,80);
		CSAW A 1 Offset(0,70);
		CSAW B 1 Offset(0,60);
		CSAW A 1 Offset(0,55);
		CSAW B 1 Offset(0,49);
		CSAW A 1 Offset(0,44);
		CSAW B 1 Offset(0,39);
		CSAW A 1 Offset(0,35);
		CSAW B 1 Offset(0,33);
		CSAW A 1 Offset(0,32);
		goto Ready;
	Spawn:
		CSAW Z -1;
		Stop;
	}
}

class ChainsawSlash : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 10;
		DamageFunction (3 * random(1, 4));
		Projectile;
		+RIPPER
		Obituary "$OB_METACHAINSAW_SLASH";
		alpha 0.5;
	}
	
	States
	{
	Spawn:
		CSLS A 8;
		stop;
	Death:
		TNT1 A 0;
		Stop;
	}
}

class MetaChainsawMeleePuff : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		damagetype "ChainsawMelee";
		RenderStyle "Translucent";
		Alpha 0.5;
		VSpeed 1;
		Mass 5;
		//AttackSound "weapons/melee/hitwall"
		SeeSound "weapons/melee/hit";
		Obituary "$OB_METAFIST";
	}
	States
	{
	Spawn:
		PUFF A 4 Bright;
		PUFF B 4;
	Melee:
		PUFF CD 4;
		Stop;
	}
}