/*
----------------------------
MetaDoom
Actor Definitions
Super Shotgun
----------------------------
*/

class MetaSuperShotgunPickup : WeaponGiver
{
	Default
	{
	DropItem "MetaSuperShotgun";
	Inventory.PickupMessage "$GOTSHOTGUN2";
	Inventory.PickupSound "weapons/ssg/get";
	}
	
	States
	{
	Spawn:
		SSG2 Z 0;
		SSG2 Z 0 { bDROPPED = 0; }
		SSG2 Z -1;
		Stop;
	}
}

class MetaSuperShotgun : MetaDoomWeapon
{
	Default
	{
	Weapon.SelectionOrder 400;
	Weapon.AmmoUse1 2;
	Weapon.AmmoUse2 2;
	Weapon.AmmoGive 8;
	Weapon.AmmoType1 "Shell";
	Weapon.AmmoType2 "Shell";
	Inventory.PickupMessage "$GOTSHOTGUN2";
	Obituary "$OB_MPSSHOTGUN";
	Tag "$TAG_SUPERSHOTGUN";
	Inventory.PickupSound "weapons/ssg/get";
	}
	
	States
	{
	Ready:
		SSG2 A 1 A_WeaponReady;
		"####" A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		Loop;
	Deselect:
		SSG2 A 1;
		SSG2 A 0 A_JumpIf(health <= 0, "DeadDude");
		SSG2 A 1 Offset(0,33) A_PlaySound("weapons/swap");
		SSG2 A 1 Offset(0,35);
		SSG2 A 1 Offset(0,39);
		SSG2 A 1 Offset(0,44);
		SSG2 A 1 Offset(0,49);
		SSG2 A 1 Offset(0,55);
		SSG2 A 1 Offset(0,60);
		SSG2 A 1 Offset(0,70);
		SSG2 A 1 Offset(0,80);
		SSG2 A 1 Offset(0,90);
	FinishDeselect:
		SSG2 A 0 A_Lower;
		Loop;
	Select:
		SSG2 A 1 Offset(0,90) A_PlaySound("weapons/ssg/use");
		SSG2 A 1 Offset(0,80);
		SSG2 A 1 Offset(0,70);
		SSG2 A 1 Offset(0,60);
		SSG2 A 1 Offset(0,55);
		SSG2 A 1 Offset(0,49);
		SSG2 A 1 Offset(0,44);
		SSG2 A 1 Offset(0,39);
		SSG2 A 1 Offset(0,35);
		SSG2 A 1 Offset(0,33);
		SSG2 A 1 Offset(0,32);
		goto Ready;
	AltFire:
	Fire:
		SSG2 A 3;
		SSG2 B 1 bright
		{
			A_FireBullets (11.2, 7.1, 20, 5, "MetaBulletPuff");
			A_PlaySound ("weapons/ssg/fire", CHAN_WEAPON);
			
			if (CountInv("PowerDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
			A_GunFlash();
			A_Quake (3,5,0,750,0);
			A_ZoomFactor(0.9,ZOOM_INSTANT|ZOOM_NOSCALETURNING);
		}
		SSG2 B 1 bright Offset(0,45) A_SetPitch(pitch-4);
		SSG2 B 1 bright Offset(0,58) { A_SetPitch(pitch-4); A_ZoomFactor(0.95,ZOOM_NOSCALETURNING); }
		SSG2 C 1 bright Offset(0,54) A_ZoomFactor(1.0,ZOOM_NOSCALETURNING);
		SSG2 C 1 bright Offset(0,48) A_SetPitch(pitch+1);
		SSG2 C 1 bright Offset(0,45) A_SetPitch(pitch+1);
		SSG2 D 1 Offset(0,42) A_SetPitch(pitch+1);
		SSG2 D 1 Offset(0,38) A_SetPitch(pitch+1);
		SSG2 D 1 Offset(0,36) A_SetPitch(pitch+2);
		SSG2 E 1 Offset(0,34) A_SetPitch(pitch+2);
		SSG2 E 1 Offset(0,33);
		SSG2 E 1 Offset(0,32) A_CheckReload();
		SSG2 FGHIJKLM 2;
		SSG2 N 2
		{
			A_PlaySound ("weapons/ssg/open", CHAN_BODY);
			if (meta_perf_spentbrass == 1)
			{
				A_FireProjectile("SSGCaseSpawner",5,0,6,4);
				A_FireProjectile("SSGCaseSpawner",5,0,6,4);
			}
		}
		SSG2 OPQ 3;
		SSG2 R 3 A_PlaySound ("weapons/ssg/load", CHAN_BODY);
		SSG2 TU 3;
		SSG2 V 1 A_PlaySound ("weapons/ssg/close", CHAN_BODY);
		SSG2 WXY 2;
		//SSG2 A 5 A_WeaponReady(WRF_NOSWITCH|WRF_NOFIRE)
		Goto Ready;
	Flash:
		TNT1 I 4 Bright A_Light1;
		TNT1 J 3 Bright A_Light2;
		Goto LightDone;
	Spawn:
		SSG2 Z -1;
		Stop;
	}
}