#library "metairon"
#include "zcommon.acs"

global int 1:mapsCleared;
// You're No Ironman!
world str 1:ironman_DeadMap;
world int 2:ironman_KillsTally;
world int 3:ironman_ItemsTally;
world int 4:ironman_SecretsTally;
world int 5:ironman_FinalScore;

Script "Ironman_Death" DEATH
{
	int cluster = GetLevelInfo(LEVELINFO_CLUSTERNUM);
	int deathmap = StrParam(s:"DEAD",i:cluster);
	ironman_DeadMap = strParam(n:PRINTNAME_LEVELNAME);
	if (GameSkill() == 666)
	{
		if (GameType() == GAME_SINGLE_PLAYER)
		{
			if(GetCvar("meta_developer"))
				log(n:0,s:" fucked up! Heading to ", s:deathmap);
			Autosave();
			Autosave();
			Autosave();
			Autosave();
			Autosave();
			FadeTo (255, 0, 0, 1.0, 0);	
			SetMusic("M_IRONMN",0);
			ChangeLevel(deathmap, 0, CHANGELEVEL_NOINTERMISSION|CHANGELEVEL_RESETHEALTH|CHANGELEVEL_RESETINVENTORY);
		}
	}
}

script "Ironman_TallyUp" UNLOADING
{
	ironman_KillsTally = ironman_KillsTally + GetLevelInfo (LEVELINFO_KILLED_MONSTERS);
	ironman_ItemsTally = ironman_ItemsTally + GetLevelInfo (LEVELINFO_FOUND_ITEMS);
	ironman_SecretsTally = ironman_SecretsTally + GetLevelInfo (LEVELINFO_FOUND_SECRETS);
	
	for(int i = 1337; i < 1400; i++)
	{
		ironman_FinalScore = ironman_FinalScore + GetActorProperty(i, APROP_Score);
	}
}

script "Ironman_StatsRun" (void)
{
	str obit;
	
	if (GetCVarString("meta_ironmantemp") == "MetaZombieMan")
		obit = "You were shot dead by a Zombieman.";
	else if (GetCVarString("meta_ironmantemp") == "MetaHellRazer")
		obit = "You were scorched in two by a Hell Razer.";
	else if (GetCVarString("meta_ironmantemp") == "MetaShotgunGuy")
		obit = "You were splattered by a Shotgun Guy.";
	else if (GetCVarString("meta_ironmantemp") == "MetaZSec")
		obit = "You were taken down by Z-Sec.";
	else if (GetCVarString("meta_ironmantemp") == "MetaMachineGunGuy")
		obit = "You were tapped by a Machinegunner.";
	else if (GetCVarString("meta_ironmantemp") == "MetaChainGunGuy")
		obit = "You were cut in half by a Chaingunner.";
	else if (GetCVarString("meta_ironmantemp") == "MetaAssassinGuy")
		obit = "You were caught by a Former Assassin.";
	else if (GetCVarString("meta_ironmantemp") == "MetaDoomImp")
		obit = "You were burned by an Imp.";
	else if (GetCVarString("meta_ironmantemp") == "MetaNightmareImp")
		obit = "You were dropped by a Nightmare Imp.";
	else if (GetCVarString("meta_ironmantemp") == "MetaDoomImpLord")
		obit = "You bowed down to the Imp Lord.";
	else if (GetCVarString("meta_ironmantemp") == "MetaHellhound")
		obit = "You were de-jugulared by a HellHound.";
	else if (GetCVarString("meta_ironmantemp") == "MetaDemonDog")
		obit = "You were de-jugulared by a Demon Dog";
	else if (GetCVarString("meta_ironmantemp") == "MetaCerberus")
		obit = "You were de-jugulared by a Cerberus";
	else if (GetCVarString("meta_ironmantemp") == "MetaDemon")
		obit = "You were devoured by a Pinky.";
	else if (GetCVarString("meta_ironmantemp") == "MetaBullDemon")
		obit = "You were slammed by a Bull Demon.";
	else if (GetCVarString("meta_ironmantemp") == "MetaSpectre")
		obit = "You were claimed by the darkness.";
	else if (GetCVarString("meta_ironmantemp") == "MetaNightmareSpectre")
		obit = "You now know why you fear the night.";
	else if (GetCVarString("meta_ironmantemp") == "MetaSawcubus")
		obit = "You were cut in half by a Sawcubus.";
	else if (GetCVarString("meta_ironmantemp") == "MetaTrite")
		obit = "You were claimed by the Trites.";
	else if (GetCVarString("meta_ironmantemp") == "MetaCacodemon")
		obit = "You were shocked by a Cacodemon.";
	else if (GetCVarString("meta_ironmantemp") == "MetaMalwraith")
		obit = "You were split up by a Malwraith.";
	else if (GetCVarString("meta_ironmantemp") == "MetaWretched")
		obit = "You were licked by a Wretched.";
	else if (GetCVarString("meta_ironmantemp") == "MetaHellKnight")
		obit = "You were slain by a Hell Knight.";
	else if (GetCVarString("meta_ironmantemp") == "MetaPainElemental")
		obit = "You were swarmed by a Pain Elemental";
	else if (GetCVarString("meta_ironmantemp") == "MetaBeholder")
		obit = "You were blinked out by a Beholder.";
	else if (GetCVarString("meta_ironmantemp") == "MetaRahovart")
		obit = "You were swarmed by Rahovart.";
	else if (GetCVarString("meta_ironmantemp") == "MetaLostSoul")
		obit = "You were swarmed by a Lost Soul.";
	else if (GetCVarString("meta_ironmantemp") == "MetaPhantom")
		obit = "You were droned out by a Phantom.";
	else if (GetCVarString("meta_ironmantemp") == "MetaArchVile")
		obit = "You became a pawn of an Arch-Vile.";
	else if (GetCVarString("meta_ironmantemp") == "MetaSummoner")
		obit = "You were evaporated by a Summoner.";
	else if (GetCVarString("meta_ironmantemp") == "MetaRevenant")
		obit = "You were pulped by a Revenant.";
	else if (GetCVarString("meta_ironmantemp") == "MetaFiend")
		obit = "You were tackled by a Fiend.";
	else if (GetCVarString("meta_ironmantemp") == "MetaBaronOfHell")
		obit = "You fell before the Baron of Hell.";
	else if (GetCVarString("meta_ironmantemp") == "MetaArachnotron")
		obit = "You were swatted by a Arachnotron.";
	else if (GetCVarString("meta_ironmantemp") == "MetaSpiborg")
		obit = "You were disintegrated by a Spiborg.";
	else if (GetCVarString("meta_ironmantemp") == "MetaMancubus")
		obit = "You were crushed by a Mancubus.";
	else if (GetCVarString("meta_ironmantemp") == "MetaBehemoth")
		obit = "You were scorched by a Behemoth.";
	else if (GetCVarString("meta_ironmantemp") == "MetaCyberManc")
		obit = "You were wasted by a Cyber-Mancubus.";
	else if (GetCVarString("meta_ironmantemp") == "MetaCyberdemon")
		obit = "You were gibbed by the Cyberdemon.";
	else if (GetCVarString("meta_ironmantemp") == "MetaSpiderMastermind")
		obit = "You were snuffed by the Spider Mastermind.";
	else if (GetCVarString("meta_ironmantemp") == "MetaMotherDemon")
		obit = "You were ended by the Mother.";
	else if (GetCVarString("meta_ironmantemp") == "MetaHellGuard")
		obit = "You were wasted by the Hell Guards.";
	else if (GetCVarString("meta_ironmantemp") == "MetaWolfensteinSS")
		obit = "You were ray-traced from existence.";
	else if (GetCVarString("meta_ironmantemp") == "MetaWolfensteinSNES")
		obit = "You were fatally bowdlerized.";
	else if (GetCVarString("meta_ironmantemp") == "MetaWolfensteinApple")
		obit = "You fell to the quirks of NTSC displays.";
	else if (GetCVarString("meta_ironmantemp") == "MetaWolfensteinMacOS")
		obit = "You went the way of Copland.";
	else if (GetCVarString("meta_ironmantemp") == "MetaWolfensteinJava")
		obit = "You took your turn and died.";
	else if (GetCVarString("meta_ironmantemp") == "Drowning")
		obit = "You went down with the ship.";
	else if (GetCVarString("meta_ironmantemp") == "Slime")
		obit = "You melted into a bubbling puddle of ooze.";
	else if (GetCVarString("meta_ironmantemp") == "Crush")
		obit = "You were pulped by the environment.";
	else if (GetCVarString("meta_ironmantemp") == "Telefrag")
		obit = "You were torn asunder from the inside-out.";
	else if (GetCVarString("meta_ironmantemp") == "Falling")
		obit = "You terminally cratered.";
	else if (GetCVarString("meta_ironmantemp") == "Suicide")
		obit = "You took the lame way out.";
	else if (GetCVarString("meta_ironmantemp") == "Exit")
		obit = "You pushed the Whopper Button. WHOO!";
	else if (GetCVarString("meta_ironmantemp") == "Extreme")
		obit = "You were painted all over the walls.";
	else if (GetCVarString("meta_ironmantemp") == "InstantDeath")
		obit = "You suffered an existence failure.";
	else if (GetCVarString("meta_ironmantemp") == "Quake")
		obit = "You were terminally shaken.";
	else
		obit = "You were killed by something really mean.";
	
	ClearInventory();
	GiveInventory("DisableHUD",1);
	SetPlayerProperty (1, 1, PROP_TOTALLYFROZEN);
	Light_Glow (2, 192, 128, 64);
	Light_Flicker (2, 192, 128);
	
	FadeTo (255, 0, 0, 1.0, 0);	
	
	Autosave();
	Autosave();
	Autosave();
	Autosave();
	Autosave();
	SetMusic("M_IRONMN",0);
	delay(8);
	FadeTo (0, 0, 0, 1.0, 1.0);
	
	delay(16);
	
	SetHudSize(320,200,1);
	SetFont("DBIGFONT");
	HudMessage(s:"Your Torment Has Ended"; HUDMSG_FADEINOUT, 0, CR_RED, 160.0, 32.0, 9999.0, 1.0, 1.0);
	delay(35);
	SetFont("SmallFont");
	HudMessage(s:obit; HUDMSG_FADEINOUT, 5, CR_RED, 160.0, 45.0, 9999.0, 1.0, 1.0);
	delay(126);
	
	if (mapsCleared <= 2)
	{
		HudMessage(s:"You accomplished nothing of significance"; HUDMSG_FADEINOUT, 6, CR_RED, 160.0, 61.0, 9999.0, 1.0, 1.0);
		delay(8);	
		HudMessage(s:"before crumbling into a bloody heap."; HUDMSG_FADEINOUT, 7, CR_RED, 160.0, 69.0, 9999.0, 1.0, 1.0);
	} else {
		HudMessage(s:"You completed ", i:mapsCleared - 2, s:" levels before"; HUDMSG_FADEINOUT, 6, CR_RED, 160.0, 61.0, 9999.0, 1.0, 1.0);
		delay(8);	
		HudMessage(s:ironman_DeadMap, s:" staked its claim."; HUDMSG_FADEINOUT, 7, CR_RED, 160.0, 69.0, 9999.0, 1.0, 1.0);
	}
	delay(32);
	HudMessage(s:"You took ", i:ironman_KillsTally, s:" monsters with you,"; HUDMSG_FADEINOUT, 8, CR_RED, 160.0, 85.0, 9999.0, 1.0, 1.0);
	delay(8);
	HudMessage(s:"but couldn't take ", i:ironman_ItemsTally, s:" items with you."; HUDMSG_FADEINOUT, 9, CR_RED, 160.0, 93.0, 9999.0, 1.0, 1.0);
	delay(8);
	HudMessage(s:"You found ", i:ironman_SecretsTally, s:" secrets."; HUDMSG_FADEINOUT, 10, CR_RED, 160.0, 101.0, 9999.0, 1.0, 1.0);
	delay(32);
	HudMessage(s:"Your final score is ", i:ironman_FinalScore, s:" points."; HUDMSG_FADEINOUT, 11, CR_RED, 160.0, 117.0, 9999.0, 1.0, 1.0);
	
	
	ChangeCamera(64,1,0);
	
	FadeTo (0, 0, 0, 0.5, 1.0);
	
	delay(30);
	
	SetMusic("M_IRONM2",0);
	
	
	
	delay(32);		
	ACS_NamedExecute("Ironman_SubtitleMessage",0);
	
	
}

script "Ironman_SubtitleMessage" (void)
{
	str deathSubtitle = "";
	
	SetHudSize(320,200,1);
	deathSubtitle = StrParam(s:"IRONMANDEAD",i:random(1,15));
	SetFont("SmallFont");
	HudMessage(l:deathSubtitle; HUDMSG_FADEINOUT, 99, CR_RED, 160.0, 150.0, 4.0, 1.0, 1.0);
	delay(215);
	restart;
}
