/*
----------------------------
MetaDoom
Actor Definitions
Tech Props
----------------------------
*/

// Big Tech Lamp
class MetaTechLamp : Actor // replaces TechLamp
{
	Default
	{
	health 5;
	Radius 16;
	Height 80;
	DeathHeight 80;
	ProjectilePassHeight -16;
	+SOLID
	+NOTAUTOAIMED
	+DONTTHRUST
	+SHOOTABLE
	+NOBLOOD
	+DONTGIB
	+RANDOMIZE
	+NOICEDEATH
	damagefactor "Fist", 0;
	damagefactor "HolyWater", 0;
	damagefactor "FireExtinguisher", 0;
	damagefactor "LightningStun", 0;
	damagefactor "Axe", 50;
	}
	
	States
	{
	Spawn:
		TLMP A 0;
		TLMP A 0 A_PlaySound("props/lighthum1", CHAN_BODY, 1.0, 1);
		TLMP A 0 A_SpawnItemEx("MetaTechLamp_Glow",0,0,68,0,0,0,0,SXF_SETMASTER);
		goto Idle;
	Idle:
		TLMP ABCD 4 Bright;
		Loop;
	Death:
		TLMP E 0 A_RemoveChildren(true,RMVF_MISC);
		TLMP E 0 A_PlaySound("props/techlamp/break");
		TLMP E 1 
		{
			A_SpawnProjectile ("MetaGibGlass", 78, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 78, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 78, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 78, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 78, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 78, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 78, 2, random(0,360), 2, 6);
		}
		TLMP E -1;
		stop;
	}
}

class MetaTechLamp_Glow : Actor
{
	Default
	{
	Renderstyle "Add";
	+NOGRAVITY
	-SOLID
	}
	
	states
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		goto Idle;
	Idle:
		TLGL A 1 bright A_Warp(AAPTR_MASTER,0,0,68,0,WARPF_NOCHECKPOSITION|WARPF_INTERPOLATE);
		loop;
	Death:
		TNT1 A 0;
		stop;
	}
}

// Small Tech Lamp
class MetaTechLamp2 : Actor // replaces TechLamp2
{
	Default
	{
	health 5;
	Radius 16;
	Height 60;
	DeathHeight 60;
	ProjectilePassHeight -16;
	+SOLID
	+NOTAUTOAIMED
	+DONTTHRUST
	+SHOOTABLE
	+NOBLOOD
	+DONTGIB
	+RANDOMIZE
	+NOICEDEATH
	damagefactor "Fist", 0;
	damagefactor "HolyWater", 0;
	damagefactor "FireExtinguisher", 0;
	damagefactor "LightningStun", 0;
	damagefactor "Axe", 50;
	}
	
	States
	{
	Spawn:
		TLP2 A 0;
		TLP2 A 0 A_PlaySound("props/lighthum1", CHAN_BODY, 1.0, 1);
		TLP2 A 0 A_SpawnItemEx("MetaTechLamp2_Glow",0,0,52,0,0,0,0,SXF_SETMASTER);
		goto Idle;
	Idle:
		TLP2 ABCD 4 Bright;
		Loop;
	Death:
		TLP2 E 0 A_RemoveChildren(true,RMVF_MISC);
		TLP2 E 0 A_PlaySound("props/techlamp/break");
		TLP2 E 1 
		{
			A_SpawnProjectile ("MetaGibGlass", 40, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 40, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 40, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 40, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 40, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 40, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 40, 2, random(0,360), 2, 6);
		}
		TLP2 E -1;
		stop;
	}
}

class MetaTechLamp2_Glow : MetaTechLamp_Glow
{
	states
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		goto Idle;
	Idle:
		TLGL A 1 bright A_Warp(AAPTR_MASTER,0,0,52,0,WARPF_NOCHECKPOSITION|WARPF_INTERPOLATE);
		loop;
	}
}

// Column
class MetaColumn : Actor // replaces Column
{
	Default
	{
	health 5;
	Radius 16;
	Height 48;
	DeathHeight 48;
	ProjectilePassHeight -16;
	+SOLID
	+NOTAUTOAIMED
	+DONTTHRUST
	+SHOOTABLE
	+NOBLOOD
	+DONTGIB
	+RANDOMIZE
	+NOICEDEATH
	damagefactor "Fist", 0;
	damagefactor "HolyWater", 0;
	damagefactor "FireExtinguisher", 0;
	damagefactor "LightningStun", 0;
	damagefactor "Axe", 50;
	}
	
	States
	{
	Spawn:
		COLU A 0;
		COLU A 0 A_PlaySound("props/lighthum3", CHAN_BODY, 1.0, 1);
		COLU A 0 A_SpawnItemEx("MetaColumn_Glow",0,0,45,0,0,0,0,SXF_SETMASTER);
		goto Idle;
	Idle:
		COLU A 1 Bright;
		Loop;
	Death:
		COLU B 0 A_RemoveChildren(true,RMVF_MISC);
		COLU B 0 A_PlaySound("props/techlamp/break");
		COLU B 1 
		{
			A_SpawnProjectile ("MetaGibGlass", 45, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 45, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 45, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 45, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 45, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 45, 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", 45, 2, random(0,360), 2, 6);
		}
		COLU B -1;
		stop;
	}
}

class MetaColumn_Glow : MetaTechLamp_Glow
{
	Default
	{
	yscale 0.5;
	}
	
	states
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		goto Idle;
	Idle:
		TLGL B 1 bright A_Warp(AAPTR_MASTER,0,0,40,0,WARPF_NOCHECKPOSITION|WARPF_INTERPOLATE);
		loop;
	}
}

// burning barrel
class MetaBurningBarrel : Actor // replaces BurningBarrel
{
	Default
	{
	health 5;
	Radius 16;
	Height 32;
	ProjectilePassHeight -16;
	+SOLID
	+NOTAUTOAIMED
	+DONTTHRUST
	+SHOOTABLE
	+NOBLOOD
	+DONTGIB
	+RANDOMIZE
	+NOICEDEATH
	+ALLOWPAIN
	damagefactor "Normal", 0;
	damagefactor "Fist", 0;
	damagefactor "HolyWater", 255;
	damagefactor "FireExtinguisher", 255;
	damagefactor "LightningStun", 0;
	damagefactor "Axe", 50;
	painchance "LightningStun", 0;
	painchance 255;
	}
	
	States
	{
	Spawn:
		FCAN A 0;
		FCAN A 0 A_PlaySound("props/burningbarrel/loop", CHAN_BODY, 1.0, 1);
	Idle:
		FCAN A 0 A_CheckSight("IdleNoSmoke");
		FCAN ABC 4 Bright A_SpawnItem("MetaBurningBarrelSmoke",0,35);
		Loop;
	IdleNoSmoke:
		FCAN ABC 4 Bright;
		goto Idle;
	Pain:
		FCAN A 0;
		FCAN A 0 A_PlaySound("barrel/hit", CHAN_VOICE);
		goto Spawn;
	Death:
		FCAN D 0;
		FCAN D 0 A_PlaySound("monsters/lostsoul/extinguish");
		FCAN DDDDDDDDDDDDDDD 1 A_SpawnItem("MetaBurningBarrelSmoke",0,35);
		FCAN D 0 A_SpawnItem("MetaBurningBarrelExtinguished");
		stop;
	}
}

class MetaBurningBarrelExtinguished : Actor
{
	Default
	{
	Radius 16;
	Height 32;
	ProjectilePassHeight -16;
	+SOLID
	+NOTAUTOAIMED
	+DONTTHRUST
	+SHOOTABLE
	+NOBLOOD
	+DONTGIB
	+RANDOMIZE
	+NOICEDEATH
	+NODAMAGE
	damagefactor "Fist", 0;
	damagefactor "HolyWater", 0;
	damagefactor "FireExtinguisher", 0;
	damagefactor "LightningStun", 0;
	damagefactor "Axe", 50;
	painchance "LightningStun", 0;
	painchance "FireExtinguisher", 0;
	painchance 255;
	}
	
	States
	{
	Spawn:
		FCAN D 4;
		loop;
	Pain:
		FCAN A 0;
		FCAN A 0 A_PlaySound("barrel/hit", CHAN_VOICE);
		goto Spawn;
	}
}

class MetaBurningBarrelSmoke : Actor
{
	Default
	{
	+NOBLOCKMAP
	+NOGRAVITY
	+ROLLSPRITE
	+ROLLCENTER
	+NOINTERACTION
	VSpeed 2;
	Renderstyle "Add";
	scale 0.5;
	alpha 0.7;
	}
	
	states
	{
	Spawn:
		FCAN Z 0 A_SetScale(frandom(0.4,0.6));
		FCAN Z 0 A_SetRoll(random(0,365));
	Idle:
		FCAN Z 0 A_SetScale(scale.x + 0.1);
		FCAN Z 2 A_FadeOut;
		loop;
	}
}

// tech pillar
class MetaTechPillar : Actor // replaces TechPillar
{
	Default
	{
	health 5;
	Radius 16;
	Height 128;
	DeathHeight 128;
	ProjectilePassHeight -16;
	+SOLID
	+NOTAUTOAIMED
	+DONTTHRUST
	+SHOOTABLE
	+NOBLOOD
	+DONTGIB
	+RANDOMIZE
	+NOICEDEATH
	damagefactor "Fist", 0;
	damagefactor "HolyWater", 0;
	damagefactor "FireExtinguisher", 0;
	damagefactor "LightningStun", 0;
	damagefactor "Axe", 50;
	}
	
	States
	{
	Spawn:
		ELEC A 0;
		ELEC A 0 A_PlaySound("props/lighthum2", CHAN_BODY, 1.0, 1);
		ELEC A -1;
		Stop;
	Death:
		ELEC B 0 A_RemoveChildren(true,RMVF_MISC);
		ELEC B 0 A_PlaySound("props/techpillar/break");
		ELEC B 1 
		{
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
			A_SpawnProjectile ("MetaGibGlass", random(40,119), 2, random(0,360), 2, 6);
		}
		ELEC B -1;
		stop;
	}
}