/*
----------------------------
MetaDoom
Actor Definitions
Corpse Props
----------------------------
*/

// Currently identical to the base game, but with some blood decals sprayed around them
// and a random chance of sprite flipping. May expand upon in future (tiny chance of flies, etc.)

class MetaDeadCacodemon : Actor //replaces DeadCacodemon
{
	States
	{
	Spawn:
		HEAD L 0;
		HEAD L 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplatBlue_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmallBlue_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmallBlue_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		HEAD L 0 A_Jump(128,2);
		HEAD L 0 { bSPRITEFLIP = 1; }
	End:
		HEAD L -1;
		Stop;
	}
}

class MetaDeadPinky : Actor //replaces DeadDemon
{
	States
	{
	Spawn:
		SARG N 0;
		SARG N 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		SARG N 0 A_Jump(128,2);
		SARG N 0 { bSPRITEFLIP = 1; }
	End:
		SARG N -1;
		Stop;
	}
}

class MetaDeadDoomImp : Actor //replaces DeadDoomImp
{
	States
	{
	Spawn:
		TROO M 0;
		TROO M 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		TROO M 0 A_Jump(128,2);
		TROO M 0 { bSPRITEFLIP = 1; }
	End:
		TROO M -1;
		Stop;
	}
}

class MetaDeadMarine : Actor //replaces DeadMarine
{
	States
	{
	Spawn:
		PLAY N 0;
		PLAY N 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		PLAY N 0 A_Jump(128,2);
		PLAY N 0 { bSPRITEFLIP = 1; }
		PLAY N 0;
	End:
		PLAY N 0 A_Jump(128,"Slop2", "Slop3", "Slop4", "Slop5", "Slop6");
		goto Slop1;
	Slop1:
		PLAY N -1;
		Stop;
	Slop2:
		DEDP A -1 A_SetScale(0.7,0.6);
		Stop;
	Slop3:
		DEDP B -1 A_SetScale(0.8,0.8);
		Stop;
	Slop4:
		DEDP C -1 A_SetScale(0.8,0.8);
		Stop;
	Slop5:
		DEDP D -1;
		Stop;
	Slop6:
		DEDP E -1;
		Stop;
	}
}

class MetaDeadShotgunGuy : Actor //replaces DeadShotgunGuy
{
	States
	{
	Spawn:
		SPOS L 0;
		SPOS L 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		SPOS L 0 A_Jump(128,2);
		SPOS L 0 { bSPRITEFLIP = 1; }
	End:
		SPOS L -1;
		Stop;
	}
}

class MetaDeadZombieMan : Actor //replaces DeadZombieMan
{
	States
	{
	Spawn:
		POSS L 0;
		POSS L 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		POSS L 0 A_Jump(128,2);
		POSS L 0 { bSPRITEFLIP = 1; }
	End:
		POSS L -1;
		Stop;
	}
}

class MetaGibbedMarine : Actor // replaces GibbedMarine
{
	States
	{
	Spawn:
		PLAY W 0;
		PLAY W 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		PLAY W 0 A_Jump(128,"End");
		PLAY W 0 { bSPRITEFLIP = 1; }
	End:
		PLAY W 0 A_Jump(128,"Slop2", "Slop3", "Slop4", "Slop5", "Slop6");
		goto Slop1;
	Slop1:
		PLAY W -1;
		Stop;
	Slop2:
		SLOP A -1;
		Stop;
	Slop3:
		SLOP B -1;
		Stop;
	Slop4:
		SLOP C -1;
		Stop;
	Slop5:
		SLOP D -1;
		Stop;
	Slop6:
		SLOP E -1;
		Stop;
	}
}