/*
----------------------------
MetaDoom
Actor Definitions
Gore Props
----------------------------
*/

class MetaCrushedProp : Actor // replaces Gibs
{
	States
	{
	Spawn:
		POL5 A 0;
		POL5 A 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		POL5 A 0 A_Jump(128,2);
		POL5 A 0 { bSPRITEFLIP = 1; }
	End:
		POL5 A -1;
		Stop;
	}
}

class MetaBrainStem : Actor // replaces BrainStem
{
	States
	{
	Spawn:
		BRS1 A 0;
		BRS1 A 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		BRS1 A 0 A_Jump(128,2);
		BRS1 A 0 { bSPRITEFLIP = 1; }
	End:
		BRS1 A -1;
		Stop;
	}
}

class MetaColonGibs : Actor // replaces ColonGibs
{
	States
	{
	Spawn:
		POB1 A 0;
		POB1 A 0
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-64,64),random(-64,64),0,0,0,0,random(0,360));
			}
		}
		POB1 A 0 A_Jump(128,2);
		POB1 A 0 { bSPRITEFLIP = 1; }
	End:
		POB1 A -1;
		Stop;
	}
}

class MetaSmallBloodPool : Actor // replaces SmallBloodPool
{
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 
		{
			for (int i = 0; i < 3; i++)
			{
				A_SpawnItemEx("BloodSplat_Permanent",random(-3,3),random(-3,3),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplat_Permanent",random(-8,8),random(-8,8),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
				A_SpawnItemEx("BloodSplatSmall_Permanent",random(-32,32),random(-32,32),0,0,0,0,random(0,360));
			}
		}
		TNT1 A 0;
		Stop;
	}
}

//bloody twitch
class MetaBloodyTwitch : Actor // replaces BloodyTwitch
{
	Default
	{
		Radius 16;
		Height 68;
		health 5;
		DeathHeight 68;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Twitching Corpse";
		//$Category "Decoration/MetaDoom"
		//$Title "Twitching Corpse (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		GOR1 A 10;
		GOR1 B 15;
		GOR1 C 8;
		GOR1 B 6;
		Loop;
	Death:
		GOR1 D 0 A_NoGravity;
		GOR1 D 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		GOR1 D -1;
		stop;
	}
}

class MetaNonsolidTwitch : Actor // replaces NonsolidTwitch
{
	Default
	{
		Radius 20;
		Height 68;
		-SOLID
		+NOGRAVITY
		+SPAWNCEILING
	}
	
	States
	{
	Spawn:
		GOR1 D 0;
		GOR1 D 0 A_SpawnItem("BloodSplat_Permanent");
		GOR1 D -1;
		wait;
	}
}

// stickiness

class MetaDeadStick : Actor // replaces DeadStick
{
	Default
	{
		Radius 16;
		Height 64;
		health 5;
		DeathHeight 64;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Corpse-Kabob";
		//$Category "Decoration/MetaDoom"
		//$Title "Corpse-Kabob (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		POL1 A -1;
		Stop;
	Death:
		POL1 B 0;
		POL1 B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		POL1 B -1;
		stop;
	}
}

class MetaLiveStick : Actor // replaces LiveStick
{
	Default
	{
		Radius 16;
		Height 64;
		health 5;
		DeathHeight 64;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Dude-Kabob";
		//$Category "Decoration/MetaDoom"
		//$Title "Dude-On-A-Stick (Breakable)"
		//$NotAngled
		//$Color 4
	}
	States
	{
	Spawn:
		POL6 A 6;
		POL6 B 8;
		loop;
	Death:
		POL1 B 0 A_NoGravity;
		POL1 B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		POL1 B -1;
		stop;
	}
}

// hanging meat (shootable)
class MetaMeat2 : Actor // replaces Meat2
{
	Default
	{
		Radius 16;
		Height 84;
		health 5;
		DeathHeight 84;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Meat 2 (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		GOR2 A -1;
		Loop;
	Death:
		GOR2 B 0 A_NoGravity;
		GOR2 B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		GOR2 B -1;
		stop;
	}
}

class MetaMeat3 : Actor // replaces Meat3
{
	Default
	{
		Radius 16;
		Height 84;
		health 5;
		DeathHeight 84;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Meat 3 (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		GOR3 A -1;
		Loop;
	Death:
		GOR3 B 0 A_NoGravity;
		GOR3 B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		GOR3 B -1;
		stop;
	}
}

class MetaMeat4 : Actor // replaces Meat4
{
	Default
	{
		Radius 16;
		Height 68;
		health 5;
		DeathHeight 68;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Meat 4 (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		GOR4 A -1;
		Loop;
	Death:
		GOR4 B 0 A_NoGravity;
		GOR4 B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		GOR4 B -1;
		stop;
	}
}

class MetaMeat5 : Actor // replaces Meat5
{
	Default
	{
		Radius 16;
		Height 52;
		health 5;
		DeathHeight 52;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Meat 5 (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		GOR5 A -1;
		Loop;
	Death:
		GOR5 B 0 A_NoGravity;
		GOR5 B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		GOR5 B -1;
		stop;
	}
}

// hanging stuff (nonsolid)
class MetaNonsolidMeat2 : Actor // replaces NonsolidMeat2
{
	Default
	{
		Radius 20;
		Height 84;
		-SOLID
		+NOGRAVITY
		+SPAWNCEILING
	}
	
	States
	{
	Spawn:
		GOR2 B 0;
		GOR2 B 0 A_SpawnItem("BloodSplat_Permanent");
		GOR2 B -1;
		wait;
	}
}

class MetaNonsolidMeat3 : Actor // replaces NonsolidMeat3
{
	Default
	{
		Radius 20;
		Height 84;
		-SOLID
		+NOGRAVITY
		+SPAWNCEILING
	}
	
	States
	{
	Spawn:
		GOR3 B 0;
		GOR3 B 0 A_SpawnItem("BloodSplat_Permanent");
		GOR3 B -1;
		wait;
	}
}

class MetaNonsolidMeat4 : Actor // replaces NonsolidMeat4
{
	Default
	{
		Radius 20;
		Height 68;
		-SOLID
		+NOGRAVITY
		+SPAWNCEILING
	}
	
	States
	{
	Spawn:
		GOR4 B 0;
		GOR4 B 0 A_SpawnItem("BloodSplat_Permanent");
		GOR4 B -1;
		wait;
	}
}

class MetaNonsolidMeat5 : Actor // replaces NonsolidMeat5
{
	Default
	{
		Radius 20;
		Height 52;
		-SOLID
		+NOGRAVITY
		+SPAWNCEILING
	}
	
	States
	{
	Spawn:
		GOR5 B 0;
		GOR5 B 0 A_SpawnItem("BloodSplat_Permanent");
		GOR5 B -1;
		wait;
	}
}

// tedious hanging dudes
class MetaHangBNoBrain : Actor // replaces HangBNoBrain
{
	Default
	{
		Radius 16;
		Height 88;
		health 5;
		DeathHeight 88;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Hanging Meat No Brain (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		HDB2 A -1;
		Loop;
	Death:
		HDBZ A 0 A_NoGravity;
		HDBZ A 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		HDBZ A -1;
		stop;
	}
}

class MetaHangNoGuts : Actor // replaces HangNoGuts
{
	Default
	{
		Radius 16;
		Height 88;
		health 5;
		DeathHeight 88;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Hanging Meat No Guts (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		HDB1 A -1;
		Loop;
	Death:
		HDBZ A 0 A_NoGravity;
		HDBZ A 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		HDBZ A -1;
		stop;
	}
}

class MetaHangTLookingDown : Actor // replaces HangTLookingDown
{
	Default
	{
		Radius 16;
		Height 64;
		health 5;
		DeathHeight 64;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Hanging Torso Looking Down (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		HDB3 A -1;
		Loop;
	Death:
		HDBZ B 0 A_NoGravity;
		HDBZ B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		HDBZ B -1;
		stop;
	}
}

class MetaHangTLookingUp : Actor // replaces HangTLookingUp
{
	Default
	{
		Radius 16;
		Height 64;
		health 5;
		DeathHeight 64;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Hanging Torso Looking Up (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		HDB5 A -1;
		Loop;
	Death:
		HDBZ B 0 A_NoGravity;
		HDBZ B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		HDBZ B -1;
		stop;
	}
}

class MetaHangTNoBrain : Actor // replaces HangTNoBrain
{
	Default
	{
		Radius 16;
		Height 64;
		health 5;
		DeathHeight 64;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Hanging Torso No Brain (Breakable)"
		//$NotAngled
		//$Color 4
	}
	States
	{
	Spawn:
		HDB6 A -1;
		Loop;
	Death:
		HDBZ B 0 A_NoGravity;
		HDBZ B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		HDBZ B -1;
		stop;
	}
}

class MetaHangTSkull : Actor // replaces HangTSkull
{
	Default
	{
		Radius 16;
		Height 64;
		health 5;
		DeathHeight 64;
		ProjectilePassHeight -16;
		+SOLID
		+NOTAUTOAIMED
		+DONTTHRUST
		+SHOOTABLE
		+DONTGIB
		+RANDOMIZE
		+NOICEDEATH
		+NOGRAVITY
		+SPAWNCEILING
		+DONTFALL
		damagefactor "HolyWater", 0;
		damagefactor "FireExtinguisher", 0;
		damagefactor "LightningStun", 0;
		damagefactor "Axe", 50;
		Tag "Fresh Meat";
		//$Category "Decoration/MetaDoom"
		//$Title "Hanging Torso No Skull (Breakable)"
		//$NotAngled
		//$Color 4
	}
	
	States
	{
	Spawn:
		HDB4 A -1;
		Loop;
	Death:
		HDBZ B 0 A_NoGravity;
		HDBZ B 0
		{
			A_PlaySound("gibbage/gib");
			
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2|CMF_BADPITCH, random (0, 160));
			}
			
			A_SpawnItemEx ("MetaGib1", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib2", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib3", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib4", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib5", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib6", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib7", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib8", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib9", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib10", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib11", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItemEx ("MetaGib12", 1, 1, random(8,32), random(0,5), random(0,5), random(8,18), random(0,360), 128, 0);
			A_SpawnItem("BloodSplat");
			bNOBLOOD = true;
		}
		HDBZ B -1;
		stop;
	}
}