/*
----------------------------
MetaDoom
ZScript Definitions
Replacement Scripts
----------------------------
*/

// Support for various random mods and TCs I like and/or have worked on
// This is mostly copy-pasted from metaoptional.zsc

// This was originally based on some really confusingly-formatted code by Matt
// (https://forum.zdoom.org/viewtopic.php?f=122&t=60916&p=1058774) but now it
// uses engine-provided functionality to do the same thing, just less grossly

// Support for various Doom 64-themed mods
class MetaDoom64Replacements : EventHandler
{
    override void CheckReplacement(ReplaceEvent e) //override void WorldTick() //WorldLoaded(WorldEvent e)
	{
		static const string oldActor[] =
		{
			// Doom 64 Consolation Prize
			"64NightmareImp","Unmaker","UnmakerUpgrade1","UnmakerUpgrade2","UnmakerUpgrade3","64MotherDemon",
			// Doom 64 for Doom 2
			"NightmareImp", "NightmareCacodemon", "D64D2Cyberdemon", "Motherdemon"
		};
		
		static const string newActor[] =
		{
			// Doom 64 Consolation Prize
			"NightmareImpSpawner","UnmakerSpawner","UnmakerKey1Spawner","UnmakerKey2Spawner","UnmakerKey3Spawner","MetaMotherDemon",
			// Doom 64 for Doom 2
			"MetaNightmareImp", "MetaMalwraith", "CyberdemonSpawner_D64D2", "MetaMotherDemon"
			
		};		

		for(int i = 0; i < oldActor.size(); i++)
		{
			if ( e.Replacee == oldActor[i] ) e.Replacement = newActor[i];			
		}
    }
}

// Replaces the EvilEye prop in SIGIL to ensure that it's funky level scripting
// works as originally intended by the legendary creator of Red Faction for nGage
class MetaSigilReplacements : EventHandler
{
    override void CheckReplacement(ReplaceEvent e)
	{		
		if (level.MapName.Left(2) ~== "E5") // thanks zombie!
		{
			if ( e.Replacee == "MetaEvilEye" ) e.Replacement = "MetaEvilEyeForSigil";	
		}
	}
}