/*
----------------------------
MetaDoom
ZScript Definitions
Menu Classes
----------------------------
*/

// Draw background graphics behind the menus. This is from JPF, so odds are
// Gutawer walked me through this like the mental infant I am.
class MetaListMenu : ListMenu
{
	int bgpicked;
	int bgnum;
	TextureID bg;
	TextureID border;
	TextureID warpy;
	
	override void Drawer ()
	{
		
		if (bgpicked == 0)
		{
			bgnum = random(1,4);
			
			if (bgnum == 1)
			{
				bg = TexMan.CheckForTexture("M_BG1", TexMan.Type_MiscPatch);
			} else if (bgnum == 2)
			{
				bg = TexMan.CheckForTexture("M_BG2", TexMan.Type_MiscPatch);
			} else if (bgnum == 3)
			{
				bg = TexMan.CheckForTexture("M_BG3", TexMan.Type_MiscPatch);
			} else if (bgnum == 4)
			{
				bg = TexMan.CheckForTexture("M_BG4", TexMan.Type_MiscPatch);
			} 
			
			bgpicked = 1;
		}
		
		border = TexMan.CheckForTexture("M_BGBRDR", TexMan.Type_MiscPatch);
		warpy = TexMan.CheckForTexture("M_BGWARP", TexMan.Type_MiscPatch);
		
		screen.DrawTexture (warpy, true, 29, 34, DTA_320x200, true);
		screen.DrawTexture (bg, true, 29, 34, DTA_320x200, true);
		screen.DrawTexture (border, true, 0, 0, DTA_320x200, true);
		
		Super.Drawer();
	}
}

class MetaFatOptionMenu : OptionMenu
{
	int bgpicked;
	int bgnum;
	TextureID bg;
	
	override void Drawer ()
	{
		
		if (bgpicked == 0)
		{
			bgnum = random(1,4);
			
			if (bgnum == 1)
			{
				bg = TexMan.CheckForTexture("M_BGFAT1", TexMan.Type_MiscPatch);
			} else if (bgnum == 2)
			{
				bg = TexMan.CheckForTexture("M_BGFAT2", TexMan.Type_MiscPatch);
			} else if (bgnum == 3)
			{
				bg = TexMan.CheckForTexture("M_BGFAT3", TexMan.Type_MiscPatch);
			} else if (bgnum == 4)
			{
				bg = TexMan.CheckForTexture("M_BGFAT4", TexMan.Type_MiscPatch);
			} 
			
			bgpicked = 1;
		}
		
		screen.DrawTexture (bg, true, 0, 0, DTA_320x200, true);
		Super.Drawer();
	}
}

// Message box menu stuff. Maybe give this a unique, smaller background or something?
class MetaMessageBoxMenu : MessageBoxMenu
{
	int bgpicked;
	int bgnum;
	TextureID bg;
	TextureID border;
	TextureID warpy;
	
	override void Drawer ()
	{
		
		/*if (bgpicked == 0)
		{
			bgnum = random(1,4);
			
			if (bgnum == 1)
			{
				bg = TexMan.CheckForTexture("M_BG1", TexMan.Type_MiscPatch);
			} else if (bgnum == 2)
			{
				bg = TexMan.CheckForTexture("M_BG2", TexMan.Type_MiscPatch);
			} else if (bgnum == 3)
			{
				bg = TexMan.CheckForTexture("M_BG3", TexMan.Type_MiscPatch);
			} else if (bgnum == 4)
			{
				bg = TexMan.CheckForTexture("M_BG4", TexMan.Type_MiscPatch);
			} 
			
			bgpicked = 1;
		}
		
		border = TexMan.CheckForTexture("M_BGBRDR", TexMan.Type_MiscPatch);
		warpy = TexMan.CheckForTexture("M_BGWARP", TexMan.Type_MiscPatch);
		
		screen.DrawTexture (warpy, true, 29, 34, DTA_320x200, true);
		screen.DrawTexture (bg, true, 29, 34, DTA_320x200, true);
		screen.DrawTexture (border, true, 0, 0, DTA_320x200, true);
		*/
		bg = TexMan.CheckForTexture("M_MSGBOX", TexMan.Type_MiscPatch);
		//screen.DrawTexture (bg, true, 0, 0, DTA_320x200, true);
		
		int w, h; [w, h] = TexMan.GetSize(bg);
		screen.DrawTexture (bg, true, ((destWidth/2) - (w/2)), ((destHeight/2) - (h/2)), DTA_VirtualWidth, destWidth, DTA_VirtualHeight, destHeight, DTA_KeepRatio, true);
		
		TextDrawer();
	}
	
	void TextDrawer ()
	{
		int i, y;
		int fontheight = textFont.GetHeight();

		y = destHeight / 2.25;

		int c = mMessage.Count();
		y -= c * fontHeight / 2;

		for (i = 0; i < c; i++)
		{
			screen.DrawText (textFont, Font.CR_UNTRANSLATED, destWidth/2 - mMessage.StringWidth(i)/2, y, mMessage.StringAt(i), DTA_VirtualWidth, destWidth, DTA_VirtualHeight, destHeight, DTA_KeepRatio, true);
			y += fontheight;
		}

		if (mMessageMode == 0)
		{
			y += fontheight;
			mMouseY = y;
			screen.DrawText(textFont, messageSelection == 0? OptionMenuSettings.mFontColorSelection : OptionMenuSettings.mFontColor, destWidth / 2, y, Stringtable.Localize("$TXT_YES"), DTA_VirtualWidth, destWidth, DTA_VirtualHeight, destHeight, DTA_KeepRatio, true);
			screen.DrawText(textFont, messageSelection == 1? OptionMenuSettings.mFontColorSelection : OptionMenuSettings.mFontColor, destWidth / 2, y + fontheight, Stringtable.Localize("$TXT_NO"), DTA_VirtualWidth, destWidth, DTA_VirtualHeight, destHeight, DTA_KeepRatio, true);

			if (messageSelection >= 0)
			{
				if ((MenuTime() % 8) < 6)
				{
					screen.DrawText(arrowFont, OptionMenuSettings.mFontColorSelection,
						destWidth/2 - 11, y + fontheight * messageSelection, selector, DTA_VirtualWidth, destWidth, DTA_VirtualHeight, destHeight, DTA_KeepRatio, true);
				}
			}
		}
	}
}