// Support for various random mods and TCs I like and/or have worked on
// This is mostly copy-pasted from metaoptional.zsc

// This was originally based on some really confusingly-formatted code by Matt
// (https://forum.zdoom.org/viewtopic.php?f=122&t=60916&p=1058774) but now it
// uses engine-provided functionality to do the same thing, just less grossly

// Support for Consolation Prize: Doom 64
class MetaDoom64Replacements : EventHandler
{
    override void CheckReplacement(ReplaceEvent e) //override void WorldTick() //WorldLoaded(WorldEvent e)
	{
		int replaceables = 8;
		
		static const string oldActor[] =
		{
			// Doom 64 Consolation Prize
			"64NightmareImp","Unmaker","UnmakerUpgrade1","UnmakerUpgrade2","UnmakerUpgrade3",
			// Doom 64 for Doom 2
			"NightmareImp", "NightmareCacodemon", "D64D2Cyberdemon"
		};
		
		static const string newActor[] =
		{
			// Doom 64 Consolation Prize
			"NightmareImpSpawner","UnmakerSpawner","UnmakerKey1Spawner","UnmakerKey2Spawner","UnmakerKey3Spawner",
			// Doom 64 for Doom 2
			"MetaNightmareImp", "MetaMalwraith", "CyberdemonSpawner_D64D2"
			
		};		

		for(int i = 0; i < (replaceables); i++)
		{
			if ( e.Replacee == oldActor[i] ) e.Replacement = newActor[i];			
		}
    }
}