// Support for Consolation Prize: Doom 64
// This is mostly copy-pasted from metaoptional.zsc

// Based on some really confusingly-formatted code by Matt
// https://forum.zdoom.org/viewtopic.php?f=122&t=60916&p=1058774

class MetaDoom64Replacements : EventHandler
{
    override void CheckReplacement(ReplaceEvent e) //override void WorldTick() //WorldLoaded(WorldEvent e)
	{
		actor actormans=null;
		array<actor>actormansdelend;		
		
		// The last entry is ignored for some stupid reason.
		int replaceables = 8;
		
		static const string oldActor[] =
		{
			// Doom 64 Consolation Prize
			"64NightmareImp","Unmaker","UnmakerUpgrade1","UnmakerUpgrade2","UnmakerUpgrade3",
			// Doom 64 for Doom 2
			"NightmareImp", "NightmareCacodemon", "D64D2Cyberdemon",
			// Thing What Makes The Array Work
			"IGNOREME"
		};
		
		static const string newActor[] =
		{
			// Doom 64 Consolation Prize
			"NightmareImpSpawner","UnmakerSpawner","UnmakerKey1Spawner","UnmakerKey2Spawner","UnmakerKey3Spawner",
			// Doom 64 for Doom 2
			"MetaNightmareImp", "MetaMalwraith", "CyberdemonSpawner_D64D2",
			// Thing What Makes The Array Work
			"IGNORETHISMAN"
			
		};		

		for(int i = 0; i < (replaceables); i++)
		{
			if ( e.Replacee == oldActor[i] ) e.Replacement = newActor[i];			
		}
    }
}