/*
----------------------------
MetaDoom
Actor Definitions
Pain Elemental
----------------------------
*/

// The original Meatball Demon, with one new nasty twist - you can no longer
// cockblock it, because it'll bite your face off.

class MetaPainElemental : MonsterCore
{
	Default
	{
		Health 400;
		Radius 31;
		Height 56;
		Mass 400;
		Speed 8;
		PainChance 128;
		Monster;
		+FLOAT
		+NOGRAVITY
		+FLOATBOB
		SeeSound "monsters/painelemental/see";
		PainSound "monsters/painelemental/pain";
		DeathSound "monsters/painelemental/die";
		ActiveSound "monsters/painelemental/idle";
		Obituary "$OB_PAINELEMENTAL";
	}

	States
	{
	Spawn:
		PAIN A 10 A_Look;
		Loop;
	See:
		"####" A 0 A_MetaBleed("FlyingBlood");
		PAIN AABBCC 3 A_Chase;
		Loop;
	Scurred:
		PAIN A 0 { bFRIGHTENED = 1; }
	ScurredLoop:
		PAIN A 0 A_GiveInventory("ScurredCounter", 1);
		PAIN A 2 A_Chase(null, null);
		PAIN A 2 A_Chase(null, null);
		PAIN A 0 A_SpawnItem("HolySweat",0,54);
		PAIN B 2 A_Chase(null, null);
		PAIN B 2 A_Chase(null, null);
		PAIN C 2 A_Chase(null, null);
		PAIN C 2 A_Chase(null, null);
		PAIN C 0 A_SpawnItem("HolySweat",0,54);
		PAIN B 2 A_Chase(null, null);
		PAIN B 2 A_Chase(null, null);
		PAIN B 0 A_JumpIfInventory("ScurredCounter", 6, "ScurredEnd");
		loop;
	ScurredEnd:
		POSS D 0
		{
			bFRIGHTENED = 0;
			A_TakeInventory("ScurredCounter",999);
		}
		goto See;
	Missile:
		PAIN D 5 A_FaceTarget;
		PAIN E 5 A_FaceTarget;
		PAIN F 5 BRIGHT A_FaceTarget;
		PAIN F 0 BRIGHT A_PainAttack("MetaLostSoul");
		Goto See;
	Melee:
		PAIN D 4 A_FaceTarget;
		PAIN E 4 A_FaceTarget;
		PAIN F 4 BRIGHT A_FaceTarget;
		PAIN F 0 BRIGHT A_CustomMeleeAttack(10, "monsters/painelemental/bite", "monsters/painelemental/bite", "PainElementalBite", 1);
		PAIN E 4 A_FaceTarget;
		Goto See;
	Pain:
		PAIN G 6;
		PAIN G 6 A_Pain;
		Goto See;
	Pain.HolyWater:
		PAIN G 3;
		PAIN G 3 A_Pain;
		Goto Scurred;
	Death:
		PAIN H 0 A_GiveToTarget("ScoreItem", 500);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		PAIN H 8 BRIGHT { bFLOATBOB = 0; }
		PAIN I 8 BRIGHT A_Scream;
		PAIN JK 8 BRIGHT;
		PAIN L 8 BRIGHT A_PainDie("MetaLostSoul");
		PAIN M 8 BRIGHT;
		Stop;
	Raise:
		PAIN MLKJIH 8;
		Goto See;
	}
}

// This horrible thing uses some mediocre custom sprite and fires out Forgotten
// Ones like a shotgun. I'd like to revise this a little one day.

class MetaBeholder : MonsterCore
{
	Default
	{
		Health 300;
		Radius 31;
		Height 56;
		Mass 400;
		Speed 8;
		PainChance 128;
		Monster;
		+FLOAT
		+NOGRAVITY
		+FLOATBOB
		SeeSound "monsters/beholder/see";
		PainSound "monsters/beholder/pain";
		DeathSound "monsters/beholder/die";
		ActiveSound "monsters/painelemental/idle";
		Obituary "$OB_BEHOLDER";
	}

	States
	{
	Spawn:
		BEHO A 10 A_Look;
		Loop;
	See:
		"####" A 0 A_MetaBleed("FlyingBlood");
		BEHO AAAAAAAA 3 A_Chase;
		Loop;
	Scurred:
		BEHO A 0 { bFRIGHTENED = 1; }
	ScurredLoop:
		BEHO A 0 A_GiveInventory("ScurredCounter", 1);
		BEHO A 2 A_Chase(null, null);
		BEHO A 2 A_Chase(null, null);
		BEHO E 0 A_SpawnItem("HolySweat",0,54);
		BEHO E 2 A_Chase(null, null);
		BEHO E 2 A_Chase(null, null);
		BEHO A 2 A_Chase(null, null);
		BEHO A 2 A_Chase(null, null);
		BEHO A 0 A_SpawnItem("HolySweat",0,54);
		BEHO E 2 A_Chase(null, null);
		BEHO E 2 A_Chase(null, null);
		BEHO E 0 A_JumpIfInventory("ScurredCounter", 6, "ScurredEnd");
		loop;
	ScurredEnd:
		BEHO D 0
		{
			bFRIGHTENED = 0;
			A_TakeInventory("ScurredCounter",999);
		}
		goto See;
	Missile:
		BEHO B 0 A_PlaySound("monsters/beholder/fire");
		BEHO B 5 A_FaceTarget;
		BEHO C 5 A_FaceTarget;
		BEHO D 5 BRIGHT
		{
			A_PainAttack("MetaForgottenOne");
			A_PainAttack("MetaForgottenOne",32,PAF_NOTARGET);
			A_PainAttack("MetaForgottenOne",64,PAF_NOTARGET);
			A_PainAttack("MetaForgottenOne",-32,PAF_NOTARGET);
			A_PainAttack("MetaForgottenOne",-64,PAF_NOTARGET);
		}
		BEHO CB 5;
		BEHO A 10;
		Goto See;
	Melee:
		BEHO B 4 A_FaceTarget;
		BEHO C 4 A_FaceTarget;
		BEHO D 4 BRIGHT A_FaceTarget;
		BEHO A 0 BRIGHT A_CustomMeleeAttack(10, "monsters/painelemental/bite", "monsters/painelemental/bite", "PainElementalBite", 1);
		BEHO A 4 A_FaceTarget;
		Goto See;
	Pain:
		BEHO E 3;
		BEHO E 3 A_Pain;
		BEHO E 6;
		Goto See;
	Pain.HolyWater:
		BEHO E 3;
		BEHO E 3 A_Pain;
		BEHO E 6;
		Goto Scurred;
	Death:
		BEHO G 0 A_GiveToTarget("ScoreItem", 500);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		BEHO H 8 BRIGHT { bFLOATBOB = 0; }
		BEHO I 8 BRIGHT A_Scream;
		BEHO J 8 BRIGHT;
		BEHO K 8 BRIGHT A_PainDie("MetaForgottenOne");
		Stop;
	}
}

// Rahovart is the Doom 64 Pain Elemental, popping out two Lost Souls at once.
// TODO: Add some interesting disadvantage

class MetaRahovart : MonsterCore
{
	Default
	{
		Health 400;
		Radius 31;
		Height 56;
		Mass 400;
		Speed 8;
		PainChance 128;
		Monster;
		+FLOAT
		+NOGRAVITY
		+FLOATBOB
		SeeSound "monsters/rahovart/see";
		PainSound "monsters/rahovart/pain";
		DeathSound "monsters/rahovart/die";
		ActiveSound "monsters/painelemental/idle";
		Obituary "$OB_RAHOVART";
	}

	States
	{
	Spawn:
		RAHO A 10 A_Look;
		Loop;
	See:
		"####" A 0 A_MetaBleed("BlueFlyingBlood");
		RAHO AAAAAAAA 3 A_Chase;
		Loop;
	Scurred:
		RAHO A 0 { bFRIGHTENED = 1; }
	ScurredLoop:
		RAHO A 0 A_GiveInventory("ScurredCounter", 1);
		RAHO A 2 A_Chase(null, null);
		RAHO A 2 A_Chase(null, null);
		RAHO D 0 A_SpawnItem("HolySweat",0,54);
		RAHO D 2 A_Chase(null, null);
		RAHO D 2 A_Chase(null, null);
		RAHO A 2 A_Chase(null, null);
		RAHO A 2 A_Chase(null, null);
		RAHO A 0 A_SpawnItem("HolySweat",0,54);
		RAHO D 2 A_Chase(null, null);
		RAHO D 2 A_Chase(null, null);
		RAHO D 0 A_JumpIfInventory("ScurredCounter", 6, "ScurredEnd");
		loop;
	ScurredEnd:
		RAHO D 0
		{
			bFRIGHTENED = 0;
			A_TakeInventory("ScurredCounter",999);
		}
		goto See;
	Missile:
		RAHO B 5 A_FaceTarget;
		RAHO C 5 A_FaceTarget;
		RAHO D 5 BRIGHT A_DualPainAttack("MetaLostSoul");
		Goto See;
	Melee:
		RAHO A 4 A_FaceTarget;
		RAHO B 4 A_FaceTarget;
		RAHO C 0 BRIGHT A_FaceTarget;
		RAHO C 4 BRIGHT A_CustomMeleeAttack(15, "monsters/painelemental/bite", "monsters/painelemental/bite", "PainElementalBite", 1);
		RAHO A 4 A_FaceTarget;
		Goto See;
	Pain:
		RAHO D 3;
		RAHO D 3 A_Pain;
		RAHO D 6;
		Goto See;
	Pain.HolyWater:
		RAHO D 3;
		RAHO D 3 A_Pain;
		RAHO D 6;
		Goto Scurred;
	Death:
		RAHO E 0 A_GiveToTarget("ScoreItem", 500);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		RAHO E 8 BRIGHT { bFLOATBOB = 0; }
		RAHO F 8 BRIGHT A_Scream;
		RAHO G 8 BRIGHT;
		RAHO H 8 BRIGHT A_PainDie("MetaLostSoul");
		RAHO IJKL 8 BRIGHT;
		Stop;
	}
}