/*
----------------------------
MetaDoom
Actor Definitions
Pain Elemental
----------------------------
*/

// The original Meatball Demon, with one new nasty twist - you can no longer
// cockblock it, because it'll bite your face off.

class MetaPainElemental : MonsterCore
{
	Default
	{
		Health 400;
		Radius 31;
		Height 56;
		Mass 400;
		Speed 8;
		PainChance 128;
		Monster;
		+FLOAT
		+NOGRAVITY
		+FLOATBOB
		SeeSound "monsters/painelemental/see";
		PainSound "monsters/painelemental/pain";
		DeathSound "monsters/painelemental/die";
		ActiveSound "monsters/painelemental/idle";
		Obituary "$OB_PAINELEMENTAL";
		Tag "Pain Elemental";
		//$Category "Monsters/MetaDoom/Pain Elemental"
		//$Title "Pain Elemental"
		//$Color 12
	}

	States
	{
	Spawn:
		PAIN A 10 A_Look;
		Loop;
	See:
		PAIN AABBCC 3 A_MetaChase;
		Loop;
	Missile:
		PAIN D 5 A_FaceTarget;
		PAIN E 5 A_FaceTarget;
		PAIN F 5 BRIGHT A_FaceTarget;
		PAIN F 0 BRIGHT A_PainAttack("MetaLostSoul");
		Goto See;
	Melee:
		PAIN D 4 A_FaceTarget;
		PAIN E 4 A_FaceTarget;
		PAIN F 4 BRIGHT A_FaceTarget;
		PAIN F 0 BRIGHT A_CustomMeleeAttack(10, "monsters/painelemental/bite", "monsters/painelemental/bite", "PainElementalBite", 1);
		PAIN E 4 A_FaceTarget;
		Goto See;
	Pain:
		PAIN G 6;
		PAIN G 6 A_Pain;
		Goto See;
	Death:
		PAIN H 0 A_GiveToTarget("ScoreItem", 500);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		PAIN H 8 BRIGHT { bFLOATBOB = 0; }
		PAIN I 8 BRIGHT A_Scream;
		PAIN JK 8 BRIGHT;
		PAIN L 8 BRIGHT A_PainDie("MetaLostSoul");
		PAIN M 8 BRIGHT;
		Stop;
	Raise:
		PAIN MLKJIH 8;
		Goto See;
	}
}

// This horrible thing fires out Forgotten Ones like a shotgun. I've redone the
// sprites, but I'd still like to revise this a little further at some point.

class MetaBeholder : MonsterCore
{
	Default
	{
		Health 300;
		Radius 31;
		Height 56;
		Mass 400;
		Speed 8;
		PainChance 128;
		Monster;
		+FLOAT
		+NOGRAVITY
		+FLOATBOB
		SeeSound "monsters/beholder/see";
		PainSound "monsters/beholder/pain";
		DeathSound "monsters/beholder/die";
		ActiveSound "monsters/painelemental/idle";
		Obituary "$OB_BEHOLDER";
		Tag "Beholder";
		//$Category "Monsters/MetaDoom/Pain Elemental"
		//$Title "Beholder"
		//$Color 12
	}

	States
	{
	Spawn:
		BEHO Z 10 A_Look;
		Loop;
	See:
		"####" A 0 
		{
			// if too close to the ground, punt the wretched up in the air
			// slightly to avoid FLOATBOB ugliness
			if (pos.z <= (floorz + 16))
			{
				ThrustThingZ(0,2,0,0);
			}
		}
		BEHO AACCBBDD 3 A_MetaChase;
		BEHO AACCBBDD 3 A_MetaChase("Melee", null);
		Loop;
	Missile:
		BEHO E 0 A_PlaySound("monsters/beholder/fire");
		BEHO E 5 A_FaceTarget;
		BEHO F 5 A_FaceTarget;
		BEHO G 5 BRIGHT
		{
			A_PainAttack("MetaForgottenOne");
			/*A_PainAttack("MetaForgottenOne",32,PAF_NOTARGET);
			A_PainAttack("MetaForgottenOne",64,PAF_NOTARGET);
			A_PainAttack("MetaForgottenOne",-32,PAF_NOTARGET);
			A_PainAttack("MetaForgottenOne",-64,PAF_NOTARGET);
			*/

			A_SpawnItemEx("MetaForgottenOne",0,0,32,8,0,0,32,SXF_NOCHECKPOSITION);
			A_SpawnItemEx("MetaForgottenOne",0,0,32,8,0,0,64,SXF_NOCHECKPOSITION);
			A_SpawnItemEx("MetaForgottenOne",0,0,32,8,0,0,-32,SXF_NOCHECKPOSITION);
			A_SpawnItemEx("MetaForgottenOne",0,0,32,8,0,0,-64,SXF_NOCHECKPOSITION);
		}
		BEHO HI 5;
		BEHO Z 10;
		Goto See;
	Melee:
		BEHO J 4 A_FaceTarget;
		BEHO K 4 A_FaceTarget;
		BEHO L 4 A_CustomMeleeAttack(10, "monsters/painelemental/bite", "monsters/painelemental/bite", "PainElementalBite", 1);
		BEHO Z 4 A_FaceTarget;
		Goto See;
	Pain:
		BEHO M 3;
		BEHO M 3 A_Pain;
		BEHO M 6;
		Goto See;
	Death:
		BEHO N 0 A_GiveToTarget("ScoreItem", 500);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		BEHO N 8 BRIGHT { bFLOATBOB = 0; }
		BEHO O 8 BRIGHT A_Scream;
		BEHO P 8 BRIGHT;
		BEHO Q 8 BRIGHT A_PainDie("MetaForgottenOne");
		BEHO RS 8 BRIGHT;
		Stop;
	}
}

// Rahovart is the Doom 64 Pain Elemental, popping out two Lost Souls at once.
// TODO: Add some interesting disadvantage

class MetaRahovart : MonsterCore
{
	Default
	{
		Health 400;
		Radius 31;
		Height 56;
		Mass 400;
		Speed 8;
		PainChance 128;
		Monster;
		+FLOAT
		+NOGRAVITY
		+FLOATBOB
		SeeSound "monsters/rahovart/see";
		PainSound "monsters/rahovart/pain";
		DeathSound "monsters/rahovart/die";
		ActiveSound "monsters/painelemental/idle";
		Obituary "$OB_RAHOVART";
		Tag "Rahovart";
		//$Category "Monsters/MetaDoom/Pain Elemental"
		//$Title "Rahovart"
		//$Color 12
	}

	States
	{
	Spawn:
		RAHO A 10 A_Look;
		Loop;
	See:
		RAHO AAAAAAAA 3 A_MetaChase;
		Loop;
	Missile:
		RAHO B 5 A_FaceTarget;
		RAHO C 5 A_FaceTarget;
		RAHO D 5 BRIGHT A_DualPainAttack("MetaLostSoul");
		Goto See;
	Melee:
		RAHO A 4 A_FaceTarget;
		RAHO B 4 A_FaceTarget;
		RAHO C 0 BRIGHT A_FaceTarget;
		RAHO C 4 BRIGHT A_CustomMeleeAttack(15, "monsters/painelemental/bite", "monsters/painelemental/bite", "PainElementalBite", 1);
		RAHO A 4 A_FaceTarget;
		Goto See;
	Pain:
		RAHO D 3;
		RAHO D 3 A_Pain;
		RAHO D 6;
		Goto See;
	Death:
		RAHO E 0 A_GiveToTarget("ScoreItem", 500);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		RAHO E 8 BRIGHT { bFLOATBOB = 0; }
		RAHO F 8 BRIGHT A_Scream;
		RAHO G 8 BRIGHT;
		RAHO H 8 BRIGHT A_PainDie("MetaLostSoul");
		RAHO IJKL 8 BRIGHT;
		Stop;
	}
}