/*
----------------------------
MetaDoom
Actor Definitions
Arachnotron
----------------------------
*/

// Currently more or less identical to the original Doom monster, behavior-wise.

class MetaArachnotron : MonsterCore
{
	Default
	{
		Health 500;
		Radius 64;
		Height 64;
		Mass 600;
		Speed 12;
		PainChance 128;
		Monster;
		+FLOORCLIP
		//+BOSSDEATH
		SeeSound "monsters/arachnotron/see";
		PainSound "monsters/arachnotron/pain";
		DeathSound "monsters/arachnotron/die1";
		ActiveSound "monsters/arachnotron/idle";
		Obituary "$OB_BABY";
		Species "BabySpider";
	}

	States
	{
	Spawn:
		BSPI AB 10 A_Look;
		Loop;
	See:
		BSPI A 20;
		"####" A 0 A_MetaBleed("FlyingBlood");
		BSPI A 3 { A_Chase(); A_PlaySound("monsters/arachnotron/walk"); }
		BSPI ABBCC 3 A_Chase;
		BSPI D 3 { A_Chase(); A_PlaySound("monsters/arachnotron/walk"); }
		BSPI DEEFF 3 A_Chase;
		Goto See+1;
	Missile:
		BSPI A 20 BRIGHT A_FaceTarget;
		BSPI G 4 BRIGHT A_SpawnProjectile("MetaArachnotronPlasma");
		BSPI H 4 BRIGHT;
		BSPI H 1 BRIGHT A_SpidRefire;
		Goto Missile+1;
	Pain:
		BSPI I 3;
		BSPI I 3 A_Pain;
		Goto See+2;
	Death:
		BSPI J 0 { bSPRITEFLIP = random(0,1); } // random chance of sprite flipping
		BSPI J 0 A_GiveToTarget("ScoreItem", 600);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		BSPI J 0 A_PlaySound("monsters/arachnotron/die2");
		BSPI J 20 A_Scream;
		BSPI K 7 A_NoBlocking;
		BSPI L 7;
		BSPI M 7 A_PlaySound("monsters/arachnotron/body");
		BSPI NO 7;
		BSPI P -1 A_KillMaster; //A_BossDeath
		Stop;
    Raise:
		BSPI P 0 { bSPRITEFLIP = 0; }
		BSPI P 5;
		BSPI ONMLKJ 5;
		Goto See+2;
	}
}

class MetaArachnotronPlasma : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 25;
		Damage 5;
		Projectile;
		+RANDOMIZE
		RenderStyle "Add";
		Alpha 0.75;
		decal "ArachnotronScorch";
		SeeSound "monsters/arachnotron/fire";
	}

	States
	{
	Spawn:
		APLS A 0 A_PlaySound ("weapons/plasmarifle/loop", CHAN_BODY, 1.0, 1);
		APLS AB 5 BRIGHT;
		Loop;
	Death:
		APBX A 0 A_PlaySound("weapons/plasmarifle/hit");
		APBX ABCDE 5 BRIGHT;
		Stop;
	}
}


// The Spiborg, a Doom 64 Arach that uses a charge beam attack. Kind of had to go
// off the reservation a bit here...

class MetaSpiborg : MonsterCore
{
	Default
	{
		Health 500;
		Radius 64;
		Height 64;
		Mass 600;
		Speed 12;
		PainChance 128;
		Monster;
		+FLOORCLIP
		//+BOSSDEATH
		SeeSound "monsters/spiborg/see";
		PainSound "monsters/arachnotron/pain";
		DeathSound "monsters/spiborg/die";
		ActiveSound "monsters/spiborg/idle";
		Obituary "$OB_SPIBORG";
		scale 0.75;
		Species "BabySpider";
	}

	States
	{
	Spawn:
		2SPI AB 10 A_Look;
		Loop;
	See:
		2SPI A 10;
		"####" A 0 A_MetaBleed("FlyingBlood");
		2SPI A 3 { A_Chase(); A_PlaySound("monsters/spiborg/walk"); }
		2SPI ABB 3 A_Chase;
		2SPI C 3 { A_Chase(); A_PlaySound("monsters/spiborg/walk"); }
		2SPI CDD 3 A_Chase;
		Goto See+1;
	Missile:
		2SPI AAAA 1 BRIGHT
		{
			A_SetPainThreshold (32);
			A_FaceTarget();
			A_SpawnProjectile("SpiborgChargeupParticle",32,0,random(-32,32),CMF_OFFSETPITCH,random(-16,16));
		}
		2SPI A 0 A_PlaySound("monsters/spiborg/charge", CHAN_WEAPON);
		2SPI BBBBBDDDDD 1 BRIGHT { A_FaceTarget(); A_SpawnProjectile("SpiborgChargeupParticle",32,0,random(-32,32),CMF_OFFSETPITCH,random(-16,16)); }
		2SPI BBBDDDBBBDDD 1 BRIGHT { A_FaceTarget(); A_SpawnProjectile("SpiborgChargeupParticle",32,0,random(-32,32),CMF_OFFSETPITCH,random(-16,16)); }
		2SPI BDBDBD 1 BRIGHT { A_FaceTarget(); A_SpawnProjectile("SpiborgChargeupParticle",32,0,random(-32,32),CMF_OFFSETPITCH,random(-16,16)); }
		2SPI E 4 BRIGHT
		{
			A_PlaySound("monsters/spiborg/fire", CHAN_WEAPON);
			A_SpawnProjectile("SpiborgPlasma",32);
			A_SetPainThreshold (0);
		}
		2SPI E 4 BRIGHT;
		2SPI E 1 A_SpidRefire;
		goto See;
	Pain:
		2SPI F 3;
		2SPI F 3 { A_Pain(); A_SetPainThreshold (0); }
		Goto See+2;
	Death:
		2SPI G 0 A_GiveToTarget("ScoreItem", 600);
		TNT1 A 0 A_SpawnItem("SoulSpawner");
		2SPI G 0 A_PlaySound("monsters/arachnotron/die2");
		2SPI G 20 A_Scream;
		2SPI G 0 { A_PlaySound("monsters/spiborg/brainpop", CHAN_7); A_SpawnItem("SpiborgBrainPop",0,56); }
		2SPI H 5 A_NoBlocking;
		2SPI I 5;
		2SPI J 5;
		2SPI K 5 A_PlaySound("monsters/arachnotron/body");
		2SPI L -1 A_KillMaster; //A_BossDeath
		Stop;
    Raise:
		2SPI P 5;
		2SPI LKJIHG 5;
		Goto See+2;
	}
}

class SpiborgPlasma : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 45;
		Damage 4;
		Projectile;
		+RANDOMIZE
		RenderStyle "Add";
		Alpha 0.75;
		Decal "PlasmaScorch";
	}

	States
	{
	Spawn:
		PLSS A 0 A_PlaySound ("weapons/plasmarifle/loop", CHAN_BODY, 1.0, 1);
		PLSE BC 2 Bright A_SpawnItem("MetaPlasmaPopTrail");
		Loop;
	Death:
		PLSE A 0 A_PlaySound("inventory/teslarocket/explode", CHAN_WEAPON);
		PLSE A 0 A_Quake (1,3,0,750,0);
		PLSE A 0 A_Explode(24,128,0);
		PLSE A 0 A_SpawnItem("ShockwaveSmall");
		PLSE B 0 bright;
		PLSE B 4 BRIGHT;
		PLSE C 3 BRIGHT;
		PLSE D 2 BRIGHT;
		Stop;
	}
}

class SpiborgBrainPop : Actor
{
	Default
	{
		scale 0.25;
		+NOINTERACTION
	}

	States
	{
	Spawn:
		MISL A 0;
		MISL B 0 
		{
			//A_Quake (3,5,0,750,0);
			for (int i = 0; i < 5; i++)
			{
				A_SpawnProjectile ("FlyingBlood", random(8,32), 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("MetaSploosh", random(8,32), 0, random (0, 360), 2, random (0, 160));
			}
			A_SpawnItem("BloodSplat");
		}
		MISL B 4 BRIGHT;
		MISL C 3 BRIGHT;
		MISL D 2 BRIGHT;
		Stop;
	}
}

class SpiborgChargeupParticle : Actor
{
	Default
	{
		Radius 3;
		Height 3;
		Speed 8;
		FastSpeed 8;
		Damage 0;
		Projectile;
		+RANDOMIZE
		+NOINTERACTION
		RenderStyle "Add";
		Alpha 1;
		scale 0.1;
	}

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 8;
		TNT1 A 0 a_scalevelocity (-2); //A_ChangeVelocity(-4, 0, 0, CVF_RELATIVE | CVF_REPLACE);
	FlyForABit:
		SBSH AAAAA 1 BRIGHT A_SetScale(scale.x + 0.1);
	Death:
		TNT1 A 0;
		Stop;
	}
}