/*
----------------------------
MetaDoom
Actor Definitions
Unique Bosses
----------------------------
*/

// The Mother Demon from Doom 64! Art from the Doom 64 for Doom 2 TC by Cage.
// Some code taken from the Doom 64 for Doom 2 TC by Mechadon.
// A good deal of attack code taken from Doom 64 Retribution by Nevander with
// lots of tweaks and edits to taste.
class MetaMotherDemon : MonsterCore
{
	Default
	{
		Health 3500;
		Radius 40;
		Height 105;
		Mass 10000;
		Speed 25;
		PainChance 4;
		Monster;
		MinMissileChance 160;
		+BOSS
		+MISSILEMORE
		+FLOORCLIP
		+NORADIUSDMG
		+DONTMORPH
		SeeSound "monsters/motherdemon/see";
		PainSound "monsters/motherdemon/pain";
		DeathSound "monsters/motherdemon/die";
		ActiveSound "monsters/motherdemon/idle";
		Obituary "$OB_MOTHERDEMON";
		damagefactor "ChaingunTurret", 0.2;
		painchance "ChaingunTurret", 0;
		painchance "Vampire", 128;
		damagefactor "Vampire", 0.25;
	}
	
	States
	{
		Spawn:
			RECT AB 10 A_Look;
			Loop;
		See:
			RECT U 0;
			RECT U 0 A_Quake(5,30,0,2048,0);
			RECT U 35 A_FaceTarget();
			goto Roam;
		Roam:
			RECT A 0 A_MetaBleed("FlyingBlood");
			RECT AAABBBCCCDDD 2 A_Chase;
			Loop;
		Missile:
		MissileClassic:
			RECT HI 6 A_FaceTarget;
			RECT J 14 Bright
			{
				A_FaceTarget();
				A_PlaySound("monsters/motherdemon/magic", CHAN_6);
				A_SpawnProjectile("MetaMotherFire", 0, 0, 0, 2, 0);
				A_SpawnProjectile("MetaMotherFire", 0, 0, 90, 2, 0);
				A_SpawnProjectile("MetaMotherFire", 0, 0, -90, 2, 0);
				A_SpawnProjectile("MetaMotherFire", 0, 0, 180, 2, 0);
			}
			RECT IEF 8 A_FaceTarget;
			RECT G 14 Bright
			{
				A_FaceTarget();
				A_PlaySound("monsters/motherdemon/fire", CHAN_7);
				A_SpawnProjectile("MetaMotherBall", 100, -16,  90); // TOP LEFT
				A_SpawnProjectile("MetaMotherBall",  40, -48,  90); // BOTTOM LEFT
				A_SpawnProjectile("MetaMotherBall", 100,  16, -90); // TOP RIGHT
				A_SpawnProjectile("MetaMotherBall", 40,  48, -90); // BOTTOM RIGHT
			}
			Goto Roam;
		Pain.Axe:
		Pain.Fist:
		Pain.BerserkFist:
		Pain:
			RECT K 3;
			RECT K 3 A_Pain;
			Goto Roam;
		Death:
			RECT L 20 A_Scream;
			RECT M 10;
			RECT N 8
			{
				A_PlaySound("monsters/motherdemon/gib", CHAN_AUTO, 1.0, 0, ATTN_NONE);
				A_Fall();
				for (int i = 0; i < 4; i++)
				{
					A_SpawnProjectile ("CyberdemonGibber", random(8,32), 0, random (0, 360), 2, random (32, 64));
					A_SpawnProjectile ("CyberdemonGibber", random(32,64), 0, random (0, 360), 2, random (64, 110));
				}
			}
			RECT O 8;
			RECT PQRS 6;
			RECT T 48;
			RECT T -1 A_KillMaster; //A_BrainDie;
			Stop;
	}
}

// Attack code ported from Doom 64 Retribution by Nevander and heavily edited.
// Sort of like a Revenant fireball, but it only tracks for a little bit after
// being spawned, which is a bit fairer given everything else going on.
class MetaMotherBall : Actor
{
	Default
	{
		Radius 11;
		Height 8;
		Speed 14;
		Damage 10;
		Projectile;
		+SEEKERMISSILE 
		+RANDOMIZE
		DeathSound "skeleton/tracex";
		Decal "RevenantScorch";
	}
	
	int trackerizer;
	
	States
	{
		Spawn:
			RBAL A 0 BRIGHT;
			RBAL A 0 A_PlaySound ("weapons/rocketlauncher/loop", CHAN_BODY, 1.0, 1);
			RBAL A 0 { trackerizer = 0; }
		Fly:
			RBAL A 0 BRIGHT A_SpawnProjectile("MetaMotherBallTrailSmoke", 0, 0, 0, 2, 0);
			RBAL A 2 BRIGHT A_SeekerMissile(5, 15, SMF_PRECISE);
			RBAL B 0 BRIGHT A_SpawnProjectile("MetaMotherBallTrailSmoke", 0, 0, 0, 2, 0);
			RBAL B 2 BRIGHT A_SeekerMissile(5, 15, SMF_PRECISE);
			RBAL A 0
			{
				// Only track for a little bit
				trackerizer++;

				if (trackerizer >= 8)
				{
					return ResolveState("StopSeeking");
				} else {
					return ResolveState(null);
				}
			}
			Loop;
		Death:
		XDeath:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("MetaRevenantTracerExplosion");
			Stop;
		StopSeeking:
			RBAL A 0 BRIGHT A_SpawnProjectile("MetaMotherBallTrailSmoke", 0, 0, 0, 2, 0);
			RBAL A 2 BRIGHT;
			RBAL B 0 BRIGHT A_SpawnProjectile("MetaMotherBallTrailSmoke", 0, 0, 0, 2, 0);
			RBAL B 2 BRIGHT;
			Loop;
	}
}

class MetaMotherBallTrailSmoke : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+DONTSPLASH
		RenderStyle "Translucent";
		Alpha 0.50;
		VSpeed 1;
	}
	
	states
	{
	Spawn:
		PUF3 ABCD 2 A_FadeOut;
	Finalize:
		PUF3 E 2 A_FadeOut;
		loop;
	}
}

class MetaMotherFire : Actor
{
	Default
	{
		Height 8;
		Radius 6;
		Damage 6;
		Speed 15;
		RenderStyle "Translucent";
		Alpha 0.50;
		damagetype "SpiderdemonTKAttack";
		PROJECTILE;
		+RANDOMIZE
		+NODAMAGETHRUST
		+FLOORHUGGER
	}
	
	States
	{
		Spawn:
			FIRE A 0;
			FIRE A 0 A_PlaySound ("monsters/motherdemon/flare", CHAN_BODY, 0.5, 1);
			FIRE ABCDE 4 BRIGHT A_SpawnProjectile("MetaMotherFireTrail", 0, 0, 0, 2, 0);
			Loop;
		Death:
			FIRE E 0 BRIGHT;
			Stop;
	}
}

class MetaMotherFireTrail : Actor
{
	Default
	{
		Height 8;
		Radius 6;
		Speed 0;
		Damage 0;
		RenderStyle "Translucent";
		Alpha 0.60;
		+NOGRAVITY
	}
	
	States
	{
		Spawn:
			FIRE ABCDE 4 BRIGHT A_FadeOut(0.20);
			Loop;
	}
}

////////////////////////////////////////////////////////////////////////////////

// The Hell Guard from Doom 2016! Art is still a problem on this one.
class MetaHellGuard : MonsterCore
{
	Default
	{
		Health 3000;
		Radius 40;
		Height 105;
		Mass 10000;
		Speed 25;
		Monster;
		MinMissileChance 160;
		+BOSS
		+MISSILEMORE
		+FLOORCLIP
		+NORADIUSDMG
		+DONTMORPH
		+NODROPOFF
		+ROLLSPRITE
		+ROLLCENTER
		SeeSound "monsters/hellguard/see";
		PainSound "monsters/hellguard/pain";
		DeathSound "monsters/hellguard/die";
		ActiveSound "monsters/hellguard/idle";
		Obituary "$OB_HELLGUARD";
		damagefactor "ChaingunTurret", 0.2;
		painchance "ChaingunTurret", 0;
		painchance "Vampire", 128;
		damagefactor "Vampire", 0.25;
	}
	
	States
	{
		Spawn:
			HGAR ZZ 10 A_Look;
			Loop;
		See:
			HGAR ] 0;
			HGAR ] 0 A_Quake(5,30,0,2048,0);
			HGAR ] 35 A_FaceTarget();
			goto Roam;
		Roam:
			HGAR A 0 A_MetaBleed("FlyingBlood");
			HGAR A 0 A_PlaySound("monsters/hellguard/step");
			HGAR AABBCC 3 A_Chase("Melee","Missile");
			HGAR A 0 A_PlaySound("monsters/hellguard/step");
			HGAR DDEECC 3 A_Chase("Melee","Missile");
			Loop;
		Melee:
			HGAR KLMN 2 A_FaceTarget;
			HGAR O 16
			{
				A_FaceTarget();
				A_Stop();
				A_PlaySound("monsters/hellknight/land",CHAN_7);
				A_Explode(64,128,XF_NOTMISSILE|!XF_HURTSOURCE);
				A_SpawnItem("BaronShockwave",32,1);
			}
			HGAR ZZ 8 A_FaceTarget;
			goto Roam;
		Missile:
			HGAR E 0 A_Jump(128, "Roll");
			HGAR E 0 A_Jump(64, "MissileFast", "TauntBefireMissileClassic");
		MissileClassic:
			HGAR E 0 A_SetRoll(0);
			HGAR FG 3 A_FaceTarget;
		MissileClassicLoop:
			HGAR H 6 A_FaceTarget;
			HGAR I 6 Bright A_FaceTarget;
			HGAR J 8 Bright
			{
				A_FaceTarget();
				A_PlaySound("monsters/hellguard/fire", CHAN_6);
				A_SpawnProjectile("MetaHellGuardShot",56,0,0);
				A_SpawnProjectile("MetaHellGuardShot",56,0,11.25);
				A_SpawnProjectile("MetaHellGuardShot",56,0,22.5);
				A_SpawnProjectile("MetaHellGuardShot",56,0,-11.25);
				A_SpawnProjectile("MetaHellGuardShot",56,0,-22.5);
			}
			HGAR H 0 A_MonsterRefire(40, "See");
			HGAR H 3 A_FaceTarget;
			Goto MissileClassicLoop;
		MissileFast:
			HGAR E 0 A_SetRoll(0);
			HGAR FG 3 A_FaceTarget;
		MissileFastLoop:
			HGAR H 2 A_FaceTarget;
			HGAR I 2 Bright A_FaceTarget;
			HGAR J 2 Bright
			{
				A_FaceTarget();
				A_PlaySound("monsters/hellguard/fastfire", CHAN_6, 1.0, 0, ATTN_NORM, 0, frandom(0.8,1.2));
				A_SpawnProjectile("MetaHellGuardShot",56,0,random(-10,10));
			}
			HGAR H 2
			{
				A_FaceTarget();
				A_CPosRefire();
			}
			loop;
		TauntBefireMissileClassic:
			HGAR KLMN 2 A_FaceTarget;
			HGAR O 6
			{
				A_FaceTarget();
				A_Stop();
				A_PlaySound("monsters/hellknight/land",CHAN_7);
				A_Explode(64,128,XF_NOTMISSILE|!XF_HURTSOURCE);
				A_SpawnItem("BaronShockwave",32,1);
			}
			HGAR KLMN 2 A_FaceTarget;
			HGAR O 6
			{
				A_FaceTarget();
				A_Stop();
				A_PlaySound("monsters/hellknight/land",CHAN_7);
				A_Explode(64,128,XF_NOTMISSILE|!XF_HURTSOURCE);
				A_SpawnItem("BaronShockwave",32,1);
			}
			HGAR Z 8 A_FaceTarget;
			goto MissileClassic;
		Roll:
			HGAR E 0 A_FaceTarget;
			HGAR E 0 A_PlaySound("monsters/hellguard/roll");
			HGAR E 0 A_Jump(64, "RollLeft");
			goto RollRight;
		RollLeft:
			HGAR C 0 ThrustThing(angle*256/360+192, 12, 0, 0);
			HGAR CQRRRRRRRRRRRRRQC 1 A_SetRoll((roll + 20));
			HGAR C 0 A_Jump(64, "MissileFast", "RollRight");
			goto MissileClassic;
		RollRight:
			HGAR C 0 ThrustThing(angle*256/360+64, 12, 0, 0);
			HGAR CQRRRRRRRRRRRRRQC 1 A_SetRoll((roll - 20));
			HGAR C 0 A_Jump(64, "MissileFast", "RollLeft");
			goto MissileClassic;
		Pain.Axe:
		Pain.Fist:
		Pain.BerserkFist:
		Pain:
			HGAR S 3 A_SetRoll(0);
			HGAR S 3 A_Pain;
			Goto Roam;
		Death:
			HGAR T 20 A_Scream;
			HGAR U 8
			{
				A_PlaySound("monsters/hellguard/gib", CHAN_AUTO, 1.0, 0, ATTN_NONE);
				A_Fall();
				for (int i = 0; i < 8; i++)
				{
					A_SpawnProjectile ("CyberdemonGibber", random(95,98), 0, random (0, 360), 2, random (32, 64));
				}
			}
			HGAR VUVUV 8;
			HGAR WXY 4;
			HGAR [ 32
			{
				A_PlaySound("bodyfalls/heavy",CHAN_6,1.0,0,ATTN_NONE,false,0.5);
				A_Quake(5,8,0,2048,0);
			}
			HGAR [ -1 A_KillMaster; //A_BrainDie;
			Stop;
	}
}

class MetaHellGuardShot : Actor
{
	Default
	{
		Radius 6;
		Height 8;
		Speed 20;
		Damage 8;
		Projectile;
		+RANDOMIZE
		RenderStyle "Add";
		Alpha 1;
		DeathSound "monsters/mancubus/boom";
		decal "Scorch";
	}

	States
	{
	Spawn:
		HGAP A 0;
		HGAP A 0 A_PlaySound("monsters/imp/fireball/loop", CHAN_BODY, 1.0, 1);
		HGAP AB 4 BRIGHT A_SpawnItem ("MetaBaronBallEffect", 0, 0, 0, 0);
		Loop;
	Death:
		HGAP C 0 A_Quake (3,5,0,750,0);
		HGAP C 8 BRIGHT;
		HGAP D 6 BRIGHT;
		HGAP E 4 BRIGHT;
		Stop;
	}
}