/*
----------------------------
MetaDoom
ZScript
Actor Definitions
----------------------------
*/

// Core Actors that a bunch of shit inherits from: define above everything else!
#include "actors/invtokens.zsc"

// Our Hero.
#include "actors/player/metadoomplayer.zsc"

// Other Stuff
#include "actors/fx.zsc"
#include "actors/blood.zsc"
#include "actors/gibs.zsc"

// Weapons
#include "actors/weapons/metacore.zsc"
#include "actors/weapons/spawners.zsc"
#include "actors/weapons/metacasings.zsc"

#include "actors/weapons/metafists.zsc"
#include "actors/weapons/metachainsaw.zsc"
#include "actors/weapons/metaaxe.zsc"
#include "actors/weapons/metapistol.zsc"
#include "actors/weapons/metashotgun.zsc"
 #include "actors/weapons/metaholywaterpistol.zsc"
#include "actors/weapons/metassg.zsc"
 #include "actors/weapons/metafireextinguisher.zsc"
#include "actors/weapons/metamachinegun.zsc"
 #include "actors/weapons/metachaingun.zsc"
#include "actors/weapons/metarocketlauncher.zsc"
 #include "actors/weapons/metagrenadelauncher.zsc"
#include "actors/weapons/metaplasmarifle.zsc"
 #include "actors/weapons/metagauss.zsc"
 #include "actors/weapons/metalightninggun.zsc"
#include "actors/weapons/metabfg.zsc"
 #include "actors/weapons/metaunmaker.zsc"
 #include "actors/weapons/metasoulcube.zsc"
 
// Items
#include "actors/items/metahealth.zsc"
#include "actors/items/metaarmor.zsc"
#include "actors/items/metaammo.zsc"
#include "actors/items/metakeys.zsc"
#include "actors/items/metapowerups.zsc"
#include "actors/items/metaloot.zsc"
#include "actors/items/metapinata.zsc"

// Inventory
#include "actors/inventory/core.zsc"
#include "actors/inventory/handgrenade.zsc"
#include "actors/inventory/teslarocket.zsc"
#include "actors/inventory/shieldwall.zsc"
#include "actors/inventory/siphongrenade.zsc"
#include "actors/inventory/hologram.zsc"
#include "actors/inventory/kineticmine.zsc"
#include "actors/inventory/theartifact.zsc"
#include "actors/inventory/dogcollar.zsc"
 #include "actors/weapons/metadoggun.zsc"
 
#include "actors/inventory/cheats.zsc"

// Monsters
#include "actors/monsters/spawners.zsc"
#include "actors/monsters/metadoomactor.zsc"

#include "actors/monsters/metazombieman.zsc"
#include "actors/monsters/metashotgunguy.zsc"

#include "actors/monsters/metalostsoul.zsc"
#include "actors/monsters/metatrite.zsc"

#include "actors/monsters/metacyberdemon.zsc"
#include "actors/monsters/metaspiderdemon.zsc"

// Props
#include "actors/props/metabarrels.zsc"
#include "actors/props/metatech.zsc"
#include "actors/props/metahell.zsc"
#include "actors/props/metagore.zsc"
#include "actors/props/metacorpses.zsc"