/*
----------------------------
MetaDoom
ZScript
Core Loading
----------------------------
*/

version "3.4"

// All Actor Definitions
#include "zscript_actors.zsc"

// Codex Stuff
#include "zscript/codex/pyparse.zsc" // Sets up the classes for parsing

#include "zscript/codex/metacodex_inventory.zsc" // The inventory items (important!)
#include "zscript/codex/metacodex_event.zsc" // Controls the inventory handouts for the codex (also important!)
#include "zscript/codex/metacodex_menu.zsc" // The menu itself (sans drawing)
#include "zscript/codex/metacodex_parser.zsc" // Parses shit
#include "zscript/codex/metacodex_drawer.zsc" // Draws shit
#include "zscript/codex/metacodex_gritty.zsc" // RenderStyle stuff written by Zombie

// Actor Replacement Scripts
#include "zscript/metaoptional.zsc"
#include "zscript/metamodreps.zsc"

// Menu Stuff
#include "zscript/metaintermission.zsc"
#include "zscript/metahud.zsc"
//#include "zscript/boa_iconlistmenu.zsc"
#include "zscript/metamenushit.zsc"
#include "zscript/nash_menu.zsc"

// Cast Call Actor
class CastCallActor : Actor
{
	Default
	{
		Health 20;
		Radius 20;
		Height 56;
		Speed 8;
		PainChance 200;
		Monster;
		+FLOORCLIP
		DeathSound "intermission/castcall1";
	}
	States
	{
	Spawn:
		TNT1 A 1 A_Look;
		Loop;
	See:
		TNT1 A 10 A_Chase;
		Loop;
	Missile:
		ENDG ABCDE 4;
		ENDG FFFFFF 9999;
		wait;
	Death:
		ENDG GHIJK 4;
		ENDG LLLLLL 9999;
		wait;
	}
}