/*
----------------------------
MetaDoom
ZScript
Core Loading
----------------------------
*/

version "4.0"

// All Actor Definitions
#include "zscript_actors.zsc"

// Codex Stuff
#include "zscript/codex/pyparse.zsc" // Sets up the classes for parsing

#include "zscript/codex/metacodex_inventory.zsc" // The inventory items (important!)
#include "zscript/codex/metacodex_event.zsc" // Controls the inventory handouts for the codex (also important!)
#include "zscript/codex/metacodex_menu.zsc" // The menu itself (sans drawing)
#include "zscript/codex/metacodex_parser.zsc" // Parses shit
#include "zscript/codex/metacodex_drawer.zsc" // Draws shit
#include "zscript/codex/metacodex_gritty.zsc" // RenderStyle stuff written by Zombie

// Actor Replacement Scripts
#include "zscript/metaoptional.zsc"
#include "zscript/metamodreps.zsc"
#include "zscript/metaloreitems.zsc"
#include "zscript/metalevelpostproc.zsc"

// Menu Stuff
#include "zscript/metaintermission.zsc"
#include "zscript/metahud.zsc"
#include "zscript/boa_iconlistmenu.zsc"
#include "zscript/metamenushit.zsc"
#include "zscript/nash_menu.zsc"

// Footsteps
#include "zscript/tzkv_footsteps.zsc"