/*
----------------------------
MetaDoom
Actor Definitions
Inventory Core
----------------------------
*/

// This is shared by all the inventory items, because being lumped with 25 pre-buff
// Shield Walls and 0 grenades seemed like a pretty shitty fate to lump a player with.
class GrenadeAmmo : Ammo
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKET";
		Inventory.Amount 1;
		Inventory.MaxAmount 25;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 25;
		Inventory.Icon "ROCKA0";
	}
	
	States
	{
	Spawn:
		ROCK A -1;
		Stop;
	}
}

// This is used to detect usage of the IDKFA cheat
// and dole out inventory items as appopriate
class MetaCheatDetector : MetaPistol
{
	Default
	{
		Weapon.SelectionOrder 0;
	}
}

// Used for inventory cool-down. When this is in the player's inventory, their
// inventory icon is greyed out and they can't use any items.
class InventoryCooldownToken : _Boolean {}