/*
----------------------------
MetaDoom
Actor Definitions
Inventory Core
----------------------------
*/

// Inventory cooldown stuff. When the player's InventoryFuel is less than the
// item's MaxAmount, the item is greyed out and can't be used, conveniently
// preventing spamming Cyberdemons to death with Siphon Grenades.
// You know who you are.

// Declare the limits in global consts so they can be changed without having to
// be redefined across multiple files. Wow, it's like I'm really in USER.CON!
const INV_COOLDOWN_GENERIC = 210; // 6 secs
const INV_COOLDOWN_SHIELD = 315; // 9 secs
const INV_COOLDOWN_HOLOGRAM = 525; // 15 secs
const INV_COOLDOWN_SIPHON = 385; // 11 secs
const INV_COOLDOWN_ARTIFACT = 595; // 17 secs

class InventoryFuel_HandGrenade : Counter 	{ Default	{ Inventory.MaxAmount INV_COOLDOWN_GENERIC; } }
class InventoryFuel_DogCollar : Counter 	{ Default	{ Inventory.MaxAmount INV_COOLDOWN_GENERIC; } }
class InventoryFuel_Hologram : Counter 		{ Default	{ Inventory.MaxAmount INV_COOLDOWN_HOLOGRAM; } }
class InventoryFuel_KineticMine : Counter 	{ Default	{ Inventory.MaxAmount INV_COOLDOWN_GENERIC; } }
class InventoryFuel_ShieldWall : Counter 	{ Default	{ Inventory.MaxAmount INV_COOLDOWN_SHIELD; } }
class InventoryFuel_SiphonGrenade : Counter { Default	{ Inventory.MaxAmount INV_COOLDOWN_SIPHON; } }
class InventoryFuel_TeslaRocket : Counter 	{ Default	{ Inventory.MaxAmount INV_COOLDOWN_SIPHON; } }
class InventoryFuel_TheArtifact : Counter 	{ Default	{ Inventory.MaxAmount INV_COOLDOWN_ARTIFACT; } }

// For making an item pickup flash after an inventory item cooldown is finished.
// Yeah, it's kinda a gross hack, but that's life, y'know?
class GimmeCooldownFlash : CustomInventory
{
	Default
	{
		+COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		+INVENTORY.ISHEALTH
		+INVENTORY.ISARMOR
	}
		
	States
	{
	Spawn:
		MEGA A 6 BRIGHT;
		Stop;
	Pickup:
		TNT1 A 0 
		{
			player.bonuscount = BONUSADD;
		}
		Stop;
	}
}	

// This is used to detect usage of the IDKFA cheat
// and dole out inventory items as appopriate
class MetaCheatDetector : MetaPistol
{
	Default
	{
		Weapon.SelectionOrder 0;
	}
}