/*
----------------------------
MetaDoom
Actor Definitions
Dog Collar
----------------------------
*/

// sleep tight pupper
class DogCollarPickup : CustomInventory
{
	Default
	{
		inventory.pickupmessage "$GOTCOLLAR";
		Tag "$TACOLLAR";
		inventory.icon "INVDOGC";
		inventory.pickupsound "inventory/dogcollar/get";
		+INVENTORY.ALWAYSPICKUP
		scale 0.5;
		+BLOCKASPLAYER
		//$Category "MetaDoom Inventory Items"
		//$Title "Dog Collar"
		//$NotAngled
		//$Color 9
	}
	
	states
	{
	Spawn:
		DOGC Z -1;
		stop;
	Pickup:
		TNT1 A 0 A_GiveInventory ("DogCollar", 1);
		//TNT1 A 0 A_GiveInventory ("GrenadeAmmo", 3);
		stop;
	}
}

class DogCollar : CustomInventory
{
	Default
	{
		inventory.pickupmessage "$GOTCOLLAR";
		Tag "$TACOLLAR";
		inventory.icon "INVDOGC";
		inventory.pickupsound "inventory/grenade/get";
		inventory.amount 1;
		inventory.maxamount 1;
		+INVENTORY.INVBAR
		scale 0.5;
	}
	
	states
	{
	Spawn:
		DOGC Z -1;
		stop;
	Use:
		TNT1 A 0
		{
			if (CountInv("InventoryFuel_DogCollar") >= INV_COOLDOWN_GENERIC)
			{
				A_PlaySound("inventory/dogcollar/toss");
				A_FireProjectile("DogCollarProj",0,0);
				A_TakeInventory("InventoryFuel_DogCollar", 999);
			} else {
				A_PlaySound("menu/invalid");
			}
		}
		fail;
	}
}

class DogCollarProj : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 15;
		DamageFunction (1);
		Projectile;
		+RANDOMIZE
		RenderStyle "Add";
		Alpha 0.75;
		damagetype "DogCollar";
	}
	
	States
	{
	Spawn:
		COLR AAAAAABBBBBBBAAAAAABBBBBBB 1 Bright;
	Fadeout:
		COLR AAAAAABBBBBBB 1 Bright A_FadeOut(0.05);
		Loop;
	Death:
		COLR A 0 
		{
			A_PlaySound("inventory/dogcollar/miss");
			A_SetTranslucent (0.75, 1);
		}
		COLR CDEF 4 Bright;
		Stop;
	}
}

class CollarSpark : Actor
{
	Default
	{
		Health 12;
		radius 3;
		height 6;
		speed .1;
		RenderStyle "Add";
		Alpha 1;
		Scale 0.5;
		Mass 0;
		+missile
		+doombounce
		+FLOORCLIP
		+DONTSPLASH
		+NOTELEPORT
	}
	
	States
	{
		COLR F 1;
		COLR FFFFF 1  Bright A_SetTranslucent(.8,1);
		COLR FFFFFF 1  Bright A_SetTranslucent(.6,1);
		COLR FFFFFFFF 1  Bright A_SetTranslucent(.4,1);
		COLR FFFFFFFFFF 1 Bright A_SetTranslucent(.2,1);
		Stop;
	}
}