// Shield Wall - Useful Edition!
class ShieldWallPiece : Actor
{
	Default
	{
	Radius 16;
	Height 56;
	+SOLID
	+WALLSPRITE
	renderstyle "add";
	}
	
	int user_lifespan;
	
	States
	{
	Spawn:
		SHWA A 0;
		SHWA A 0 A_PlaySound("inventory/shieldwall/start");
		SHWA A 0
		{
			A_SetAngle(angle + 90);
			A_PlaySound("inventory/shieldwall/loop",6,1,1);
		}
	LifeSpan:
		SHWA AB 4 BRIGHT;
		SHWA A 0 { user_lifespan++; }
		SHWA A 0 A_JumpIf(user_lifespan == 32, "Die");
		Loop;
	Die:
		SHWA A 0 A_PlaySound("inventory/shieldwall/end",6);
		TNT1 A 0;
		stop;
	}
	
	// Ignore player shots, but still block the enemy's
	override bool CanCollideWith(Actor other, bool passive)
	{
		if (passive && other.target is "MetaDoomPlayer" && !other.bISMONSTER)
		{
			return false;
		} 
		
		return true;
	}

}